### ISSUE TITLE
Example Using Two Connections

### ISSUE THREAD

**Issue by jamescarr** [doctrine/DoctrineORMModule#122]
My app that I am refactoring to use doctrine has different database connections for both of the modules. The documentation says that it's possible to register multiple database connections but I cannot for the life of me figure out how to do it.

An example would be helpful!

**Comment by bakura10** [comment]
I'm closing this long lasting issue, as it seems the doc for setting two connections is [now present](https://github.com/doctrine/DoctrineORMModule/blob/master/docs/configuration.md#how-to-use-two-connections).
