### ISSUE TITLE
Authentication with more than one Entity

### ISSUE THREAD

**Issue by herodrigues** [doctrine/DoctrineORMModule#212]
I want to know if it's possible to do more than one authentication like this: 

``` php
return array(
    'doctrine' => array(
        'authentication' => array(
            'orm_default' => array(
                'object_manager' => 'Doctrine\ORM\EntityManager',
                'identity_class' => 'Application\Entity\User',
                'identity_property' => 'email',
                'credential_property' => 'password',
            ),
           // I've tried, but doesn't work
           'another' => array(
                'object_manager' => 'Doctrine\ORM\EntityManager',
                'identity_class' => 'Application\Entity\AnotherUser',
                'identity_property' => 'email',
                'credential_property' => 'password',
            ),
        ),
    ),
);
```

Basically, if I have two tables for users, but one is most different than another, and I need to decide which entity I have to authenticate.

Is this supported?

Already asked here: http://stackoverflow.com/questions/16218483/multiple-identity-properties-for-authentication-in-zf2-with-doctrine-2

Sorry my english :D

**Comment by faghihian71** [comment]
@Ocramius so please introduce some  links to us to  find out how we can do it

**Comment by gianarb** [comment]
@faghihian71 try to follow this link
http://framework.zend.com/manual/current/en/modules/zend.authentication.intro.html#adapters
