### ISSUE TITLE
Custom type mapping (always generate database update)

### ISSUE THREAD

**Issue by ThaDafinser** [doctrine/DoctrineORMModule#267]
If you register a custom type, it may always get updated in the database using
php index.php orm:schema-tool:update
(although there is no real change)

I think it's easier to read these requests:
https://github.com/symfony/symfony/issues/2810  (= Solution for Symfony)
http://www.doctrine-project.org/jira/browse/DBAL-63
http://www.doctrine-project.org/jira/browse/DBAL-42

My solution for now in Module.php:
```php
    public function onBootstrap(MvcEvent $event)
    {
        /* @var $em \Doctrine\ORM\EntityManager */
        $em = $event->getApplication()
            ->getServiceManager()
            ->get('Doctrine\ORM\EntityManager');
        
        //this is needed to avoid unnecessary custom type updates...
        $em->getConnection()
            ->getDatabasePlatform()
            ->markDoctrineTypeCommented(Type::getType('myCustomType'));
    }
```

Don't know if this should come into the Module, but even if not.

Maybe someone will be happy to find this solution :smile:

**Comment by gianarb** [comment]
Thanks for this experience! :)
