### ISSUE TITLE
Can't save user entity with association of type __PHP_Incomplete_Class

### ISSUE THREAD

**Issue by personman** [doctrine/DoctrineORMModule#277]
This was working until I did some updating in composer. I'm not entirely sure which package changed to cause this, but when I save my user entity now, I get this error:

```
Fatal error: Uncaught exception 'Doctrine\ORM\ORMException' with message 
'Found entity of type __PHP_Incomplete_Class on association Mrss\Entity\User#college, 
but expecting Mrss\Entity\College' in 
[...]/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 783
```

This seems to be related to this issue here: http://www.doctrine-project.org/jira/browse/DDC-1698

But I'm not sure how to fix it.

**Comment by sks40gb** [comment]
9880808080n8098098089

**Comment by aburcheri** [comment]
I solved it with running command 
`./vendor/bin/doctrine-module orm:generate:proxies`
