### ISSUE TITLE
Implement a entity listener resolver as a abstractpluginmanager 

### ISSUE THREAD

**Issue by macnibblet** [doctrine/DoctrineORMModule#292]

**Comment by jbenoit2011** [comment]
The `EntityListenerResolver` implementation proposed by @j-schumann is very simple, easy to understand and moreover do the job!
Anybody to suggest a PR?

**Comment by TomHAnderson** [comment]
Closed for lack of PR

**Comment by cbichis** [comment]
It's possible to get such entity listener resolver for ZF3/Laminas ?
