### ISSUE TITLE
DoctrineModule\Stdlib\Hydrator\DoctrineObject checking for setter using method_exists()

### ISSUE THREAD

**Issue by rafaame** [doctrine/DoctrineORMModule#294]
Hello,

In the method hydrateByValue of DoctrineObject you are checking if the method_exists().

The problem is I made a base class for entities that traps the setters and getters in __call, but it won't work since you check the existence of the method.

May you consider changing this verification?

Thanks!

**Comment by gianarb** [comment]
Hi @rafaame this problem persist?
Thanks!

**Comment by gianarb** [comment]
I close this issue for inactivity.
Thanks
