### ISSUE TITLE
Installation error with message DoctrineModule can't be initialised

### ISSUE THREAD

**Issue by baymaro** [doctrine/DoctrineORMModule#298]
Following the installation process you describe, i'm getting a Fatal error  Fatal error : DoctrineModule can't be initialized. After some unsuccessfull search i rename module folders in ./vendor to DoctrineModule and DoctrineORMModule to suit the declaration in config/application.config.php. Then i add ./vendor/doctrine to module paths. and then the errors went away. But i' wonder if it is a right way as no one seems to have face that issue before

**Comment by gianarb** [comment]
I close this issue for inactivity.
If this problem persist write here and I reopen this issue :)
Thanks
