### ISSUE TITLE
Move from YUML-based graphing to pulpo-based metadata graphs

### ISSUE THREAD

**Issue by Ocramius** [doctrine/DoctrineORMModule#327]
See http://www.pulpo18.com/ - pretty much self-explanatory.

**Comment by Blaimi** [comment]
how do you want to include the binary? Include via composer all 4 variants and make an OS-Swith? Can that conflict with the [tems of use](https://help.skipper18.com/general-information/basic-information/terms-of-use)? Disable the feature if no binary is configured? Display an error message “pulpo not found. Please download at pulpo18.com and configure path in zdt.config.php”? OS-Specific Autodownloader (terms)?

I think the best solution would be the ability to configure the path and provide an autodownloader if it is not found.

**Comment by TomHAnderson** [comment]
I'll close this issue unless someone has more to add?
