### ISSUE TITLE
CLI incompatible with TranslatorAwareTreeRouteStack

### ISSUE THREAD

**Issue by pfx2** [doctrine/DoctrineORMModule#333]
When using TranslatorAwareTreeRouteStack instead of SimpleRouteStack in a ZF2 application, cli launches this error if the application is adding a translator on the router:

Fatal error: Call to undefined method Zend\Mvc\Router\Console\SimpleRouteStack::setTranslator() in /home/pierrick/www/paroledemome/module/Application/Module.php on line 28

Steps to reproduce :

1) In Application's module.config.php:

return array(
...
'router' => array(
        'router_class' => 'Zend\Mvc\Router\Http\TranslatorAwareTreeRouteStack',
...
     )
)

2) In Application's Module.php:

public function onBootstrap(MvcEvent $e) {
...
// Routes translation
$router = $serviceManager->get('router');
$router->setTranslator($translator);
...

It seems that DoctrineORMModule is unable to detect the router_class and always use  SimpleRouteStack.

**Comment by diegolaciar** [comment]
I have the same problem !  If I use TranslatorAwareTreeRouteStack the console throw that error.
