### ISSUE TITLE
WAMP Error - File mapping drivers must have a valid directory path

### ISSUE THREAD

**Issue by tigs001** [doctrine/DoctrineORMModule#341]
I have been developing a project on Linux and everything works well.  I thought I'd bring the project across to the WAMP environment on Windows 7 (Home, 32 bit) and I come across the following problem:

```
$ ./vendor/doctrine/doctrine-module/bin/doctrine-module -v orm:validate-schema

  [Doctrine\Common\Persistence\Mapping\MappingException]
  File mapping drivers must have a valid directory path, however the given pa
  th [C:\develop\web\vp1\module\Directory\config/../src/Directory/Entity] see
  ms to be incorrect!
```

So it would appear in the above that it wants me to use Windows "\" characters as a path separator, not Unix "/" characters, however if I change this in my configuration, my code will not longer be portable back to Linux.

Any suggestions or workarounds ?

**Comment by jogoool** [comment]
I have the same problem with symfony 3.4 after cloned my project to windows 10 machine.
