### ISSUE TITLE
Activate cache in doctrine 2 in a project using zend framework 2

### ISSUE THREAD

**Issue by maySaghira** [doctrine/DoctrineORMModule#348]
Hi , i'm new in doctrine so here is my configuration in zend framework :

``` php
 // Doctrine config
     'doctrine' => array(
        'driver' => array(
            __NAMESPACE__ . '_driver' => array(
                'class' => 'Doctrine\ORM\Mapping\Driver\AnnotationDriver',
                'cache' => 'array',
                'paths' => array(__DIR__ . '/../src/' . __NAMESPACE__ . '/Entity')
            ),
            'orm_default' => array(
                'drivers' => array(
                    __NAMESPACE__ . '\Entity' => __NAMESPACE__ . '_driver'
                )
            )
        )
    ),
```

i need to activate the cache in doctrine 2 , how can i make do it ?
thanks.

**Comment by maurymmarques** [comment]
I'm facing the same problem using MacOS 10.10, Apache 2.4.9, PHP 5.5.14 and ZendFramework 2.2

Notice: Array to string conversion in /Library/WebServer/Documents/myproject/vendor/doctrine/doctrine-module/src/DoctrineModule/Options/Driver.php on line 89

That message appers when I'm with "display_errors = On" in php.ini, but when I turn off "display_errors" my project runs correctly.

**Comment by Ocramius** [comment]
@maurymmarques open a new issue and debug the issue first.
