### ISSUE TITLE
handleRequiredField shoud not override Zend Required annotation

### ISSUE THREAD

**Issue by duyld-qsoftvn** [doctrine/DoctrineORMModule#349]
I use Zend form Required annotation for marking an element is required, but ElementAnnotationsListener always override it.

In the case below, this form field is not required because the field in database is nullable.
```php
/**
 * @ORM\Column(length=30, nullable=true)
 * @Form\Options({"label":"Display name"})
 * @Form\Required(true)
 */
protected $displayName;
```

It can be better if ElementAnnotationsListener check for this value has been set before set it again.

**Comment by gianarb** [comment]
Hi! Maybe this issue was resolved with this code
https://github.com/doctrine/DoctrineORMModule/blob/b1e178f70588e90f6b7d6e0266c975ced85c9ede/src/DoctrineORMModule/Form/Annotation/ElementAnnotationsListener.php#L221

Can you check this stuff? I reopen this issue if persist
