### ISSUE TITLE
PDOSqlsrv Driver with MS-SQL instance name not working with port

### ISSUE THREAD

**Issue by maggo2801** [doctrine/DoctrineORMModule#350]
If I use den PDOSqlsrv Driver with a MS-SQL servername including an instance name, the connection can't be created because of the port definition.

http://php.net/manual/de/ref.pdo-sqlsrv.connection.php#113550

Qoute:
The above worked with and without port (,1433). I also noticed adding the instance name (MSSQLSERVER) after the server name with a slash (), as in "Server=foo-sql\MSSQLSERVER" caused a failure to connect.

Is it possible to disable the port usage in dsn string creation?

**Comment by NewtonsNerds** [comment]
@maegnes Thank you, that helped me solve the problem. It's still not easy to believe Doctrine would set the port to be 3306 by default.

**Comment by manishkumbhkar** [comment]
I am still facing this issue as I already tried with making port to nul but not able to connected

**Comment by maegnes** [comment]
@NewtonsNerds could you please be a bit more specific or post some your doctrine configuration?

**Comment by maegnes** [comment]
@manishkumbhkar could you please be a bit more specific or post some your doctrine configuration?
