### ISSUE TITLE
Cli problems with doctrine/orm dev-master

### ISSUE THREAD

**Issue by prolic** [doctrine/DoctrineORMModule#351]
Using DoctrineORMModule with Doctrine ORM 2.4.* having no database set up I can run this:

    php public/index.php

Updating Doctrine-ORM to 2.5-dev-master leeds to an exception

    php public/index.php

Leads to:

    Doctrine\DBAL\Driver\PDOException: SQLSTATE[HY000] [1049] Unknown database 'app_db' in /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 47

Last exception was:

    Zend\ServiceManager\Exception\ServiceNotCreatedException: An exception was raised while creating "Router"; no instance returned in /home/sasa/code/dimabay/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php on line 909
The only difference is the composer.json settings.

What kind of feature is denying the router to be created and requiring a db connection every time?

**Comment by bakura10** [comment]
Hi,

Do you still have this issue @prolic ?

**Comment by prolic** [comment]
I will retest it again and let you know tomorrow.

**Comment by prolic** [comment]
yeah, problem seems to be gone away. thanks ;)
