### ISSUE TITLE
How to load Doctrine driver xml mappings from external package?

### ISSUE THREAD

**Issue by pdrosos** [doctrine/DoctrineORMModule#354]
Hello,

I am using the Payum library in my Zend Framework 2 project with Doctrine. 
In the Payum/Core package there are a couple of base models:
https://github.com/Payum/Core/tree/master/Model 
which I need to extend with my own entities.

They have XML mapping here:
https://github.com/Payum/Core/tree/master/Bridge/Doctrine/Resources/mapping
and I need to load these mappings in my module.

My doctrine configuration is:
```php
'doctrine' => array (
    'driver' => array (
        'Payum_models' => array (
            'class' => 'Doctrine\ORM\Mapping\Driver\SimplifiedXmlDriver',
            'cache' => 'array',
            'paths' => array(
                __DIR__ . '/../../../vendor/payum/payum/src/Payum/Core/Bridge/Doctrine/Resources/mapping',
            )
        ),
        __NAMESPACE__ . '_entities' => array (
            'class' => 'Doctrine\ORM\Mapping\Driver\AnnotationDriver',
            'cache' => 'array',
            'paths' => array(
                __DIR__ . '/../src/' . __NAMESPACE__ . '/Entity',
            )
        ),
        'orm_default' => array(
            'drivers' => array(
                'Payum\Core\Model' => 'Payum_models',
                __NAMESPACE__ . '\Entity' => __NAMESPACE__ . '_entities',
            )
        )
    )
),
```
And I receive the following error:
```
[Doctrine\Common\Persistence\Mapping\MappingException]
File mapping drivers must have a valid directory path, however the given path 0 seems to be incorrect!
```
Could you please help me how to configure the Payum Core Doctrine mappings correctly?

Thank you in advance!

**Comment by bakura10** [comment]
Hi,

I suspect that the path is simply wrong. Apart from that the configuration seems good. I've made a module that use XML models: https://github.com/zf-fr/zfr-cash/blob/initial/config/module.config.php#L70

Try to compare the paths of mine and yours :). I'm closing as there is high probability that mistake comes from that, and XML works as expected in Doctrine ORMModule, do not hesitate to ping me if you still do not find the issue.

**Comment by stefanorg** [comment]
just in case anyone look at this, the correct configuration for SimplifiedXmlDriver is:
```
'Payum_models' => array (
            'class' => 'Doctrine\ORM\Mapping\Driver\SimplifiedXmlDriver',
            'cache' => 'array',
            'paths' => array(
                __DIR__ . '/../../../vendor/payum/payum/src/Payum/Core/Bridge/Doctrine/Resources/mapping' => 'Payum\Core\Model',
            )
        ),
```

We need to specify the namespace prefixes ` ... => Payum\Core\Model`
