### ISSUE TITLE
2nd Connection not having correct configuration

### ISSUE THREAD

**Issue by Perfect-Web** [doctrine/DoctrineORMModule#362]
I have setuped a 2nd connection besides `orm_default` and after trying to enable the cache, i realized that it is not working. From preliminary tests it seems that my configs (at least for the cache) are replaced with the default ones `array`

Any idea what could be ?

**Comment by gianarb** [comment]
Hi @Perfect-Web this problem persist?
Thanks

**Comment by gianarb** [comment]
I close this issue for inactivity.
If this problem persist write here and I reopen this issue :) 
DoctrineModule has a lot of configuration this stuff confuse a lot of people.
We are working to build docs and to collect experience to propose different solutions :)
Thanks
