### ISSUE TITLE
No Indexes in MySQL

### ISSUE THREAD

**Issue by gmuehl** [doctrine/DoctrineORMModule#368]
Not sure if it is a Bug of the DoctrineORMModule, though, custom Indexes are not Created. When i add the following Code to the Comment of the Class Definition

    @ORM\Table(
        name="test",
        indexes={
            @ORM\Index(name="test_idx", columns={"testfield"})
        }
    )

NOTHING happens! Not even a Error Message, the Doctrine Tool tells me, that the Table is still in Sync. After that i add the Index manually in MySQL and the Doctrine Tool tells me, that the Table is no longer in Sync and wants to drop the Index. For me it looks like the "indexes" Part is totally ignored, though, i have no Idea why and where to put the Bug Report?

**Comment by Ocramius** [comment]
This is likely related to doctrine/dbal#769
