### ISSUE TITLE
Support resolver of interfaces

### ISSUE THREAD

**Issue by bakura10** [doctrine/DoctrineORMModule#370]
With the recent addition in Doctrine ORM 2.5 for resolving interface names everywhere, DoctrineORMModule needs to be updated:

https://github.com/doctrine/DoctrineORMModule/blob/1d5b0fdda6200836b0d1dcf637d36e35ea48ad6c/src/DoctrineORMModule/Service/EntityResolverFactory.php#L45

This line has to be changed to 

```php
$eventManager->addEventSubscriber($targetEntityListener);
```

I'm not sure if this is possible to do it without breaking BC until Doctrine 2.5 is out.

**Comment by Ocramius** [comment]
Good point :-\

**Comment by bakura10** [comment]
Fixed by #374
