### ISSUE TITLE
Problem getting MAX() value in DQL

### ISSUE THREAD

**Issue by JoostvdB94** [doctrine/DoctrineORMModule#371]
The entry in the result array where the maximum value should be (and is in normal SQL) is empty. 

Maybe this is caused by the use of DATE_DIFF inside MAX?

```
$em->createQuery('SELECT d.action, d.environmentId,MAX(DATE_DIFF(d.timeStart,d.timeDone)) AS max_value FROM DBMAINTANANCE as d GROUP BY d.environmentId,d.action');
```
The result array is:

```
Array ( [action] => copy [environmentId] => 5 [max_value] => )
```

**Comment by Ocramius** [comment]
This is not a `DoctrineORMModule` specific issue, closing.

Consider posting it to stackoverflow or the doctrine mailing list instead.
