### ISSUE TITLE
Many to many relationships are not cached.

### ISSUE THREAD

**Issue by jarrettj** [doctrine/DoctrineORMModule#381]
Second level cache does not cache many to many relationships. I've noticed that there's no example with a many to many relationship. Is this a bug or not supported?

**Comment by gianarb** [comment]
I don't find other issues about this thing.
This problem persist?

Thanks

**Comment by jarrettj** [comment]
Hi,

I don't think enough people are using the 2nd level cache as yet. But with the release of it in doctrine 2.5 it should rear its head more.

I have a workaround, I simple evictCollectionRegions() from cache. Not optimal, but it works. Will have a look to see if the latest version is fixed.

**Comment by gianarb** [comment]
Ok thanks for this experience.. I close it

**Comment by JoschaP** [comment]
This issue persists as it is described by @jarrettj 
The cache misses and puts at every request but never read from cache..

Any Solution here?
