### ISSUE TITLE
PDO Exception after updating

### ISSUE THREAD

**Issue by Grrompf** [doctrine/DoctrineORMModule#382]
After updating from 0.7 to 0.8 I get a PDOException -> Access denied for user: 

    PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[28000] [1045]     Access denied for user 'nakade'@'localhost' (using password: YES)' in /home/mumm/workspace/nakade/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43

No problems if I fallback to 0.7

**Comment by Ocramius** [comment]
This information is incomplete.

Additionally, 0.7 is not supported since a long time.

**Comment by Grrompf** [comment]
This Error is reproducable... and it occurs if I update from the version in use 0.7 to 0.8 using composer update.  Gimme a hint if you are interested in more details ... the left message stack has no information of value....

PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[28000] [1045] Access denied for user 'nakade'@'localhost' (using password: YES)' in /home/mumm/workspace/nakade/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
Stack trace:
#0 /home/mumm/workspace/nakade/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('mysql:host=loca...', 'nakade', '*****', Array)
#1 /home/mumm/workspace/nakade/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(45): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=loca...', 'nakade', '*****', Array)
#2 /home/mumm/workspace/nakade/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'nakade', '*****', Array)
#3 /home/mumm/workspace/nakade/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): Doctrine\DBAL\Connection->connect()
#4 /home/mumm/workspace/nakade/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\ in /home/mumm/workspace/nakade/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php on line 930

**Comment by Ocramius** [comment]
It isn't reproducible without complete information and config...

**Comment by Grrompf** [comment]
what do you need? more than database.local?

**Comment by Ocramius** [comment]
Complete stack trace, as well as the string parameters of the methods in the stack trace

**Comment by Grrompf** [comment]
this is the complete stack trace thrown by the composer during update

**Comment by Ocramius** [comment]
That shows up to `#4`

**Comment by Grrompf** [comment]
yes... as I pc the trace in the comment.... want a screenshot?

**Comment by Grrompf** [comment]
the command and when the error was thrown (never seen that before using composer)

composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)                   
Generating autoload files
PHP Fatal error:  ..... and the stacktrace as posted

**Comment by Grrompf** [comment]
the composer.json

"require": {
        "php": ">=5.5",
        "highcharts": "4.0.4",
        "zendframework/zendframework": "~2.3",
        "doctrine/common": "~2.4",
        "zendframework/zendpdf": "~2.0",
        "dompdf/dompdf": "dev-master",
        "dino/dompdf-module": "~0.3",
        "zendframework/zendservice-recaptcha": "~2.0",
        "doctrine/doctrine-orm-module": "0.7",  ---> ~0.7 == Exception
        "zf-commons/zfc-rbac": "~2.4",
        "geoip/geoip": "~1.14",
        "snapshotpl/zf-snap-geoip": "~2.0",
        "zf-commons/zfc-twig": "~1.2",
        "twig/extensions" : "~1.0",
        "umpirsky/twig-gettext-extractor": "dev-master",
        "saeven/zf2-circlical-trans": "dev-master"

  }

**Comment by Ocramius** [comment]
Seems like one of those modules is trying to operate during update: I don't think it is a good idea.

Also, the stack trace is incomplete ;-)
