### ISSUE TITLE
Collections doesnt keep index

### ISSUE THREAD

**Issue by cbichis** [doctrine/DoctrineORMModule#387]
Hi,

When creating collections at hydrating the index association is not maintained.

``` php
/**
 * @ORM\Entity
*/

class My1 {
...
@Annotation\ComposedObject({"target_object":"Test\Entity\My2", "is_collection":true, "options":{"count":0, "should_create_template":true, "allow_add":true, "allow_remove":true}})
...
}
```

So after I hydrate the main entity with DoctrineHydrator for any collection within entity the index association is not maintained. This makes impossibly so at a later point to know which My2 object from collection should be used to work with the object...

**Comment by gianarb** [comment]
Hi! Have you resolved this problem?

Thanks
