### ISSUE TITLE
Filters factory

### ISSUE THREAD

**Issue by Perfect-Web** [doctrine/DoctrineORMModule#391]
I have searched a way to use the service factory in registering filters in doctrine, however from what i saw in the code this is not currently possible since the name of the filter class is directly passed to doctrine and not routed thru the service manager.

Any ideas ?

**Comment by Perfect-Web** [comment]
@Ocramius any hints on this ?

**Comment by gianarb** [comment]
Hi @Perfect-Web have you see this section of `module.config`?
Thanks
https://github.com/doctrine/DoctrineORMModule/blob/61827e4ed682727ac83de88c3cdb8075e71a53c2/config/module.config.php#L82

**Comment by Perfect-Web** [comment]
Yes, however this doesnt go thru the service locator is it ?
https://github.com/doctrine/DoctrineORMModule/blob/61827e4ed682727ac83de88c3cdb8075e71a53c2/src/DoctrineORMModule/Service/ConfigurationFactory.php#L64

**Comment by gianarb** [comment]
Oh yes! I don't know this feature but maybe you can try to add other filters with this approach..
```php
return array(
    'doctrine' => array(
        'connection' => array(
            'orm_default' => array(
                'params' => array(
                    'host'     => 'localhost',
                    'port'     => '3306',
                    'user'     => 'username',
                    'password' => 'password',
                    'dbname'   => 'database',
                )
            ),
        ),
        'configuration' => array(
            'orm_default' => array(
                'filters'           => array(
                        "name-filter" => "Class\Your\Filter"
                ),
        )
    )
)
```

**Comment by Perfect-Web** [comment]
that doesnt solve my problem, they still wont go thru the service locator ...

**Comment by gianarb** [comment]
oh sorry.. I have tried to read a few code in `doctrine2` but I don't find a good method to add filter because the api support `$config->addFilter("name", "className");` and I don't find a method to change this flow in this moment..

Feedback from your test? :)

**Comment by Perfect-Web** [comment]
none atm, maybe will be a support with future versions of doctrine

**Comment by TomHAnderson** [comment]
This hydration module solves this problem: https://github.com/phpro/zf-doctrine-hydration-module#hydrator-configuration
