### ISSUE TITLE
zf2, doctrine 2 redis cache

### ISSUE THREAD

**Issue by ASNOMO** [doctrine/DoctrineORMModule#393]
Hello,
We have big project on zf2 with doctrine 2 integrated. 
Now we have two problems:
1. we change cache adapter from filesystem to redis and project stand slower, why so? Redis cache must be faster than filesystem cache!
2. we cache only metadata and query, and doctrine use all redis memory limit. On our server memory limit is 3Gb and it is two much for metadata and query. I think something doesnot work properly. Can you help us ?

**Comment by Ocramius** [comment]
Hi @ASNOMO, I'm closing this issue as it doesn't look like an issue with the repository, rather than a tech support request: this is where you usually hire someone to get support on your own codebase instead.
