### ISSUE TITLE
Deprecated error with "symfony/console" v2.7.0-BETA1

### ISSUE THREAD

**Issue by basarevych** [doctrine/DoctrineORMModule#397]
PHP Deprecated:  "Symfony\Component\Console\Helper\DialogHelper" is deprecated since version 2.5 and will be removed in 3.0. Use "Symfony\Component\Console\Helper\QuestionHelper" instead.

**Comment by gianarb** [comment]
Thanks! Would you submit a PR? :)

**Comment by basarevych** [comment]
I would if i were familiar with symfony but I'm not...

**Comment by gianarb** [comment]
@basarevych this issue is solved here
e1855a6
I close this issue thanks
