### ISSUE TITLE
No longer works with zf-commons/zfc-user 1

### ISSUE THREAD

**Issue by jarrettj** [doctrine/DoctrineORMModule#403]
Hi,

Using zf-commons/zfc-user no longer works with doctrine/doctrine-orm-module. I get the following error from composer:

```
Problem 1
    - zf-commons/zfc-user-doctrine-orm 1.0.0 requires doctrine/doctrine-orm-module 0.* -> no matching package found.
    - zf-commons/zfc-user-doctrine-orm 1.0.0 requires doctrine/doctrine-orm-module 0.* -> no matching package found.
    - Installation request for zf-commons/zfc-user-doctrine-orm 1.* -> satisfiable by zf-commons/zfc-user-doctrine-orm[1.0.0].
```

But I know this has worked before. I use the master branch to enable 2nd level cache in doctrine using ZF2.

Any help please.

Thanks.

**Comment by gianarb** [comment]
DoctrineORMModule 0.9.0 supports 2nd level cache... 
can you try to explicit this version in your composer.json?
Thanks

**Comment by jarrettj** [comment]
It works. Thanks.

Initially I had been using doctrine/doctrine-orm-module master to get the 2nd level cache to work. Did not know that the zendframework/zendframework 2.4 release had added 2nd level cache updates.

It works not using  zendframework/zendframework 2.4 and doctrine/doctrine-orm-module 0.9.

Thanks.

Cheers.

**Comment by gianarb** [comment]
Happy!
