### ISSUE TITLE
Underscore Naming Strategy

### ISSUE THREAD

**Issue by mesaugat** [doctrine/DoctrineORMModule#404]
Is there a way to enable the Underscore Naming Strategy for Doctrine ORM via the config? Would be great.

**Comment by codeliner** [comment]
Yes it is. Check out this config: https://github.com/codeliner/php-ddd-cargo-sample/blob/master/config/autoload/global.php

It needs to be known by the service manager. I use the class name as service name. 
But you can choose another name if you want.

**Comment by mesaugat** [comment]
Thanks. :+1:

**Comment by codeliner** [comment]
you are welcome

**Comment by zeleniy** [comment]
@codeliner the link is not available yet

**Comment by codeliner** [comment]
@zeleniy Structure changed in the last years (it's now a zend expressive app), but config is still the same: https://github.com/codeliner/php-ddd-cargo-sample/blob/master/config/autoload/dependencies.global.php#L29
