### ISSUE TITLE
custom walker

### ISSUE THREAD

**Issue by Perfect-Web** [doctrine/DoctrineORMModule#406]
Any feature to support this ?

.. code-block:: php

```
<?php

$config = new \Doctrine\ORM\Configuration();
$config->setDefaultQueryHints(
    'doctrine.customOutputWalker' => 'MyProject\CustomOutputWalker'
);
```

**Comment by Perfect-Web** [comment]
I have created 3 pull request, all 3 are belonging to this features. thanks

**Comment by gianarb** [comment]
o.O and why 3 PRs?

**Comment by bakura10** [comment]
Laziness of not wanting to fork the project and instead doing the PR through GitHub interface I suppose?

Anyway, thanks @Perfect-Web but please do a proper PR: fork the project, create a new branch, do your changes and submit it again (with tests) :). Thanks in advance!

**Comment by Perfect-Web** [comment]
indeed laziness is the perfect word, i will do a PR for this, i need a push from behind once in a while i suppose :P

**Comment by gianarb** [comment]
eheh we wait your PRs :) Can you close all others? Thanks

**Comment by Perfect-Web** [comment]
done with #410
