### ISSUE TITLE
Error installation DoctrineORM

### ISSUE THREAD

**Issue by chiara79** [doctrine/DoctrineORMModule#411]
Hi guys, 
I'm trying to set doctrine with this command `php composer.phar require doctrine/doctrine-orm-module`  and version `0.*` but I get this error:

**Could not load package bilge/doctrine-module in http://packagist.org: [UnexpectedValueException] Could not parse version constraint ^0.8: Invalid version string "^0.8"**

Why?

**Comment by Ocramius** [comment]
`bilge/doctrine-module`? /cc @gianarb

**Comment by guilhermeblanco** [comment]
```bash
composer self-update
```

Only a few weeks ago composer added `^` support.

**Comment by Ocramius** [comment]
Yeah, but still, why is it grabbing that fork?

**Comment by chiara79** [comment]
ok doing `php composer.phar self-update` now it works.
Thanks guys :)

**Comment by gianarb** [comment]
selfupdate I love you! :D
