### ISSUE TITLE
orm:convert-mapping doesn't works 

### ISSUE THREAD

**Issue by chiara79** [doctrine/DoctrineORMModule#412]
Hi guys,
I'm trying to use the command:
 `php ./vendor/doctrine/doctrine-module/bin/doctrine-module orm:generate-entities ./module/Album/src/ --generate-annotations=true `

but I get this error:
**No Metadata Classes to process.**

If I try the command 
`php ./vendor/doctrine/doctrine-module/bin/doctrine-module orm:convert-mapping --namespace="Album\\Entity\\" --force --from-database annotation ./module/Album/src/` the entity is created.

#### composer.json
 ```json
{
  "require": {
    "php": ">=5.4.0",
    "zendframework/zendframework": "2.4.*",
    "bjyoungblood/bjy-authorize": "1.4.*",
    "doctrine/doctrine-orm-module": "^0.9.0"
  },
  "require-dev": {
    "zendframework/zend-developer-tools": "dev-master",
    "zendframework/zftool": "dev-master"
  }
}
 ```
#### doctrine.local.php in autoload
 ```php
<?php
return [
    'doctrine' => [
        'connection' => [
            'orm_default' => [
                'driverClass' => 'Doctrine\DBAL\Driver\PDOMySql\Driver',
                'params' => [
                    'host' => 'localhost',
                    'port' => '3306',
                    'user' => 'myuser',
                    'password' => 'mypass',
                    'dbname' => 'mydb',
                    'driverOptions' => [
                        PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8'
                    ]
                ]
            ]
        ]
    ]
];
 ```
#### doctrine.config.php in my module Album:
 ```php
<?php
return [
    'doctrine' => [
        'driver' => [
            'Album_driver' => [
                'class' => 'Doctrine\ORM\Mapping\Driver\AnnotationDriver',
                'cache' => 'array',
                'paths' => [
                    __DIR__ . '/../src/Album/Entity'
                ]
            ],
            'orm_default' => [
                'drivers' => [
                    'Album\Entity' =>  'Album_driver'
                ],
            ],
        ],
    ],
];
 ```

why?

**Comment by chiara79** [comment]
someone help me?

**Comment by hieuit7** [comment]
`"vendor/bin/doctrine" orm:convert-mapping --from-database --namespace Application\Entity\ annotation module\Application\src\`
it's working with me!!
but i running in window. In linux you can run with `"vendor/bin/doctrine" = php ./vendor/doctrine/doctrine-module/bin/doctrine-module` or `php ./vendor/bin/doctrine` 

and command to generates entity:
`"vendor/bin/doctrine" orm:generate-entities --generate-annotations=true module\Application\src\`

**Comment by Lionelsan95** [comment]
If the message is "No Metadata Classes to process" it means that there is no php's files that doctrine can generate

So you should check again if the file is there

You have to know also that "orm:generate:entities" command is used to complete an existing php's script no to create it is not like in symfony when you use the "doctrine:generate:entity" command line.

I hope that it will help you.

**Comment by Ocramius** [comment]
Closing: just misconfiguration (likely path based)
