### ISSUE TITLE
0.8.0: Console usage throws fatal error after dependency updates

### ISSUE THREAD

**Issue by arekkas** [doctrine/DoctrineORMModule#416]
After running `php composer.phar update`, I receive

```
Fatal error: Uncaught exception 'ErrorException' with message '"Symfony\Component\Console\Helper\DialogHelper" is deprecated since version 2.5 and will be removed in 3.0. Use "Symfony\Component\Console\Helper\QuestionHelper" instead.' in /home/www/athene2.serlo.org/athene2/src/vendor/symfony/console/Helper/DialogHelper.php:34
Stack trace:
#0 [internal function]: exception_error_handler(16384, '"Symfony\\Compon...', '/home/www/athen...', 34, Array)
#1 /home/www/athene2.serlo.org/athene2/src/vendor/symfony/console/Helper/DialogHelper.php(34): trigger_error('"Symfony\\Compon...', 16384)
#2 /home/www/athene2.serlo.org/athene2/src/vendor/doctrine/doctrine-orm-module/src/DoctrineORMModule/Module.php(144): Symfony\Component\Console\Helper\DialogHelper->__construct()
#3 [internal function]: DoctrineORMModule\Module->initializeConsole(Object(Zend\EventManager\Event))
#4 /home/www/athene2.serlo.org/athene2/src/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Event in /home/www/athene2.serlo.org/athene2/src/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php on line 930
```

when running a php cli command.

My composer.json file is:

```json
    "require": {
        "doctrine/doctrine-orm-module": "0.8.0",
        "widmogrod/zf2-assetic-module": "1.3.*",
        "zf-commons/zfc-rbac": "2.3",
        "php": ">=5.5",
        "zf-commons/zfc-base": "0.*",
        "zendframework/zendframework": "2.3.*",
        "neilime/zf2-twb-bundle": "2.3.0",
        "zendframework/zend-developer-tools": "~0.0.2",
        "dnode/dnode": "dev-master",
        "stroker/cache": "dev-master",
        "zf-commons/zfc-twig": "dev-master",
        "umpirsky/twig-gettext-extractor": "1.1.*",
        "ewgo/solarium-module": "~1.0"
    },
    "config": {
        "vendor-dir": "src/vendor"
    }
```

**Comment by arekkas** [comment]
Bumping doctrine orm module to 0.9.0 solves this issue. Fortunately, there aren't any BC breaks afaict :)

**Comment by Ocramius** [comment]
Closing - already solved in the bump.

**Comment by seyfer** [comment]
I think `0.8.3` should be released with fix

**Comment by Ocramius** [comment]
0.9.x was already released. Unless @gianarb has time to upgrade, I would rather suggest you to move to `~0.9.0`

After all, this kind of breakage happened because you upgraded to symfony 2.7 ;-)

**Comment by seyfer** [comment]
@Ocramius , i'm using Zend and Symfony components is only dependencies to other libs including Doctrine. It had been upgraded by dependency, not by my wish.

And I can't move to 0.9 because I have another modules binded to 0.8 and I can't change them
```
infoclient dev-master requires doctrine/doctrine-orm-module 0.8.* -> no matching package found.
```
So...

**Comment by Ocramius** [comment]
Fair enuff. @gianarb your decision - afaik, the patch that fixed this introduced some changes, so I'm not sure if it can be backported.

**Comment by gianarb** [comment]
mm ok tomorrow I pull 0.9.1 with a few fixes and 0.8.1 with this fix..

Good?

**Comment by mpalourdio** [comment]
While you're at it, change this https://github.com/doctrine/DoctrineModule/blob/master/composer.json#L37 and https://github.com/doctrine/DoctrineORMModule/blob/master/composer.json#L42 to ```"symfony/console": "~2.7"```

**Comment by gianarb** [comment]
Hi @mpalourdio I prefer to apply this type of fix
https://github.com/doctrine/DoctrineORMModule/commit/4ee848a6bfdfb9d02db10218c99a99cab5ebca70

What do you think?

**Comment by mpalourdio** [comment]
QuestionHelper existed in 2.5 anyway https://github.com/symfony/Console/tree/2.5/Helper
There's no need to make a test if you want to replace DialogHelper to have lower symfony dependencies IMO

**Comment by gianarb** [comment]
I don't see bc break..  
I thought yours proposal and in my opinion is a good idea update symfony/console ~2.7.. This version is LTS and we can removev my horrible `if else` in module.php
