### ISSUE TITLE
Wrong Version Number in Tag 0.9.0

### ISSUE THREAD

**Issue by FabianKoestring** [doctrine/DoctrineORMModule#419]
In `DoctrineORMModule/src/DoctrineORMModule/Version.php` on tag `0.9.0` version is set to `VERSION = '0.8.0';`.

**Comment by gianarb** [comment]
Thanks! I'm ready to fix it in the next release..
e951409cb46ff625e4d691c0a32d49e383e58ee4 :)

Cose
