### ISSUE TITLE
Connection fatal exception before module initialization because of initializeConsole event

### ISSUE THREAD

**Issue by gpsa** [doctrine/DoctrineORMModule#421]
When I use zf2 in console mode, "initializeConsole" event is thrown by DoctrineORMModule.
This is a problem. For example, if I have many console commands that didn't use database connection, or, as in my case, I need to catch database/entity exceptions without exit script execution.

Is it possible to have a way to disable it by default, I mean don't initializeConsole "orm_default" was not provided into my module config, or even passing a new key for disabling it?

Whatever is the response, is there any problem if I detach this event 'doctrine', 'loadCli.post'?
What is the way to disable this event?

It looks like this issue: #383

**Comment by gpsa** [comment]
For while I just put in module:

/**
     * {@inheritDoc}
     */
    public function init(ModuleManagerInterface $manager) {
        /* @var $events \Zend\EventManager\SharedEventManager */
        $events = $manager->getEventManager()->getSharedManager();

        /* Remove a inicialização do evento doctrine "initializeConsole" */
        /* @var $queue \Zend\Stdlib\CallbackHandler */
        foreach ($events->getListeners('doctrine', 'loadCli.post') as $queue) {
            $callback = $queue->getCallback();
            if(is_array($callback) && $callback[1] == "initializeConsole")
            {
                $events->detach('doctrine', $queue);
                break;
            }
        }
    }

**Comment by Ragazzo** [comment]
Same here

**Comment by gpsa** [comment]
In Your Module.php class, you can try this:

/**
     * {@inheritDoc}
     */
    public function init(ModuleManagerInterface $manager)
    {
        if (!stristr($_SERVER['PHP_SELF'], 'doctrine')) {
            /* @var $events \Zend\EventManager\SharedEventManager */
            $events = $manager->getEventManager()->getSharedManager();

            /* Remove a inicialização do evento doctrine "initializeConsole" */
            /* @var $queue \Zend\Stdlib\CallbackHandler */
            foreach ($events->getListeners('doctrine', 'loadCli.post') as $queue) {
                $callback = $queue->getCallback();

                if (is_array($callback) && $callback[1] == "initializeConsole") {
                    $events->detach('doctrine', $queue);
                    break;
                }
            }
        }
    }

**Comment by Ragazzo** [comment]
Ok , thanks
