### ISSUE TITLE
Uncaught PDOException while using Doctrine CLI in ZF2

### ISSUE THREAD

**Issue by sinlord** [doctrine/DoctrineORMModule#422]
Hi,
    I am getting an uncaught PDO Exception while trying to use the doctrine CLI. I am following marco's tutorial: http://marco-pivetta.com/doctrine-orm-zf2-tutorial/#/ 

Configurations are: 
ZF 2.5.1 with PHP version 5.5.21
Zend Server 8.0.2
MySQL version: 14.14 Distrib 5.5.27, for osx10.6 (i386) using readline 5.1
-----------------------------------
abhinavs-MacBook-Pro-2:website-lawkanoon ABHI$  ./vendor/bin/doctrine-module orm:validate-schema
![zf2- doctrine-module folder structure](https://cloud.githubusercontent.com/assets/4741645/8230000/6b5f0824-15bc-11e5-80c3-04d4fa358ba7.png)
![doctrine-module-linked-path](https://cloud.githubusercontent.com/assets/4741645/8230003/710211a4-15bc-11e5-8322-d65a3cca4f4b.png)

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] No such file or directory' in /usr/local/zend/apache2/htdocs/website-lawkanoon/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
Stack trace:
#0 /usr/local/zend/apache2/htdocs/website-lawkanoon/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('mysql:host=loca...', 'root', '', Array)
1. /usr/local/zend/apache2/htdocs/website-lawkanoon/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(45): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=loca...', 'root', '', Array)
2. /usr/local/zend/apache2/htdocs/website-lawkanoon/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'root', '', Array)
3. /usr/local/zend/apache2/htdocs/website-lawkanoon/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): Doctrine\DBAL\Connection->connect()
4. /usr/local/zend/apache2/htdocs/website-lawkanoon/vendor/doctrine/dba in /usr/local/zend/apache2/htdocs/website-lawkanoon/vendor/zendframework/zend-servicemanager/src/ServiceManager.php on line 946
---------------------------
Could anyone please help? @Ocramius any suggestions please?

**Comment by gianarb** [comment]
I'm not @Ocramius but I try anyway.
This problem is not of Doctrine but there are a connection's problem between PHP and MYSQL..

Can you try to connect in mysql with the bash client for example? Thanks

**Comment by sinlord** [comment]
Hi @gianarb ,
    Many thanks for your response. I am able to connect to MySQL using bash ( I can login using the same credentials using the specified command:  /usr/local/zend/mysql/bin/mysql -u root ), as well as set up correctly my module mapping using the Doctrine connection settings defined in doctrine.local.php file. This seems to work fine until I try to access CLI and validate mapping or create DB schema.
    Furthermore, is there any other way apart from CLI to generate Database schema?

**Comment by gianarb** [comment]
`This seems to work` what does it means?  Web works and in CLI no?
Can you try to use PDO in a php script and to run it into the terminal? :)

Thanks

**Comment by sinlord** [comment]
Hi @gianarb ,
    Thanks again for your response. Web worked fine. It was just the CLI which did not work. As I said I was able to also successfully set up my module mapping and see the mapping appear in the zend developer toolbar.
   After playing around and reading about similar issues in Symphony, I changed the host parameter in   the doctrine.local.php file from 'localhost'  to  '127.0.0.1' (Thus having defined  'host'     => '127.0.0.1', ). This did the trick and CLI started working. 
I am not sure if I am the only mac (os x Yosemite) user that would have encountered this issue, hence would request adding this to the notes if possible. Many thanks again for your prompt reply and help.
Cheers,
ABHI

**Comment by gharbi-m-decade** [comment]
i've had the same issue on Redhat and changing host from 'localhost' to '127.0.0.1' was the solution as you've said.
So i thank you :+1:
