### ISSUE TITLE
Support for Mirrored Databases

### ISSUE THREAD

**Issue by ryanheath86** [doctrine/DoctrineORMModule#424]
Good Morning,

I have a quick question to which I cannot find the answer anywhere. I wonder if you can help. 

I have a big customer that is wanting to mirror their SQL database and implement a witness server to handle failover. Is there any support within doctrine to connecting to such a setup?

Any advice would be very much appreciated
Regards

**Comment by gianarb** [comment]
Hi @ryanheath86 what is your configuration in detail?! There are a few drivers to manage custom configuration of mysql.. Example mysqlnd or mysql_proxy but few features are transparent for your application.

i don't understand your question :sob:

**Comment by TomHAnderson** [comment]
This request has exprired.
