### ISSUE TITLE
Configuration naming strategy in ORMModule

### ISSUE THREAD

**Issue by merorafael** [doctrine/DoctrineORMModule#426]
Hi guys,

I searched the documentation and found nothing about it. How could set the name strategy to underscore the DoctrineORMModule settings?

Naming strategy doc:
http://doctrine-orm.readthedocs.org/en/latest/reference/namingstrategy.html

**Comment by codeliner** [comment]
See this issue #404 ;)

**Comment by merorafael** [comment]
Thanks :+1:

**Comment by gianarb** [comment]
I close this question
