### ISSUE TITLE
Expected Collection, got ArrayCollection

### ISSUE THREAD

**Issue by halesk** [doctrine/DoctrineORMModule#441]
Hi, I'm having an issue with my mapping: 
```
Expected value of type "Doctrine\Common\Collections\Collection|array" for association field "LMS\Model\Program#$visios", got "Doctrine\Common\Collections\ArrayCollection" instead.
```
Is this exception normal? Should I investigate my code? I triple checked that my "LMS\Model\Program#$visios" is instanced with a "new Doctrine\Common\Collections\ArrayCollection()" in the constructor.  I have tried multiple different mappings already but this error always comes up.

Thanks for any guidance.

**Comment by Ocramius** [comment]
There is something fishy going on. Maybe show the bit of code causing it, and dump the values inside your entity?

**Comment by halesk** [comment]
First thank for you quick response.
You are right something is wrong somewhere. In "LMS\Model\Program#$visios" I have an ArrayCollection at the index 0 and my "Visio" entity at the index 1.
I continue to investigate my code but just for the record this var_dump at UnitOfWorl@843: 
```
var_dump($entry.' '.$targetClass->name);
```
just before the crash gives me this:
```
'Doctrine\Common\Collections\ArrayCollection@000000003f9adf7b00000000ff6d39d7 LMS\Model\VisioSession' 
```

This is my mapping for "LMS\Model\Program#$visios":
```
    /**
     * @ORM\ManyToMany(targetEntity="VisioSession")
     * @ORM\JoinTable(name="program_visios",
     *      joinColumns={@ORM\JoinColumn(name="program_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="visio_id", referencedColumnName="id")}
     *      )
     */
    protected $visios;
```

**Comment by halesk** [comment]
Ok I got it.
After the POST of my form I tried to add manually my VisioSession to the Program, which was already done by the Doctrine binding. So I had two different elements (ArrayCollection AND VisioSession) side by side in "LMS\Model\Program#$visios".

Sorry for the stupid question and thank you again for guidance. That exception have me a headache.
