### ISSUE TITLE
ORA-01862 error in PHP 7

### ISSUE THREAD

**Issue by arcostasi** [doctrine/DoctrineORMModule#444]
I'm having the following error with doctrine-orm-module 0.9.2 in PHP 7:

ORA-01862: the numeric value does not match the length of the format item in /var/www/arcostasi.bs2.com.br/verifica.crmall.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php:76

Any Solution? Thanks.

**Comment by gianarb** [comment]
Hello this is our of scope, please create this issue in the correct project
https://github.com/doctrine/dbal

I see that there are different dbal builds that fail with PHP7.
Thanks!

**Comment by arcostasi** [comment]
Hello Gianluca, I reported to the DBAL issues! Thanks.

**Comment by Ocramius** [comment]
Ref: doctrine/dbal#2256
