### ISSUE TITLE
Doctrine Pagination With Left Join (ArrayCollection)

### ISSUE THREAD

**Issue by ibekiaris** [doctrine/DoctrineORMModule#446]
Hi there. I have the following query:

       $qb->select(array('c', 'd'))
            ->from($this->_rps('Client'), 'c')
            ->where('c.account = :account');

        if ($searchTerm) {
            $qb->andWhere('c.title LIKE :term');
            $qb->setParameter('term', '%' . $searchTerm . '%');
        }

        $qb->leftJoin('c.domains', 'd');
        $qb->setFirstResult($offset)->setMaxResults($limit);
        $qb->setParameter('account', $account);

        $query = $qb->getQuery();
        $paginator = new Paginator($query, false);

        return $paginator;

This is not working correctly. Only if I remove left join everything works fine. I have also tried new Paginator($query, true)... 

I there any effective way to work with that returning always a paginator object?

Thank you in advance

**Comment by Ocramius** [comment]
Not an issue of the module.

Also, please describe what "is not working correctly", if you re-open this against https://github.com/doctrine/doctrine2
