### ISSUE TITLE
Downgrade (wrong release marked as latest)

### ISSUE THREAD

**Issue by thexpand** [doctrine/DoctrineORMModule#451]
I updated doctrine via composer, and the versions of all doctrine dependencies have downgraded.

> Updating dependencies (including require-dev)
  - Installing ocramius/proxy-manager (1.0.2)
  - Removing symfony/console (v3.0.1)
  - Installing symfony/console (v2.8.2)
  - Removing doctrine/dbal (v2.5.4)
  - Installing doctrine/dbal (v2.4.5)
  - Installing doctrine/migrations (v1.3.0)
  - Removing doctrine/orm (v2.5.4)
  - Installing doctrine/orm (v2.4.8)
  - Removing doctrine/doctrine-module (0.10.0)
  - Installing doctrine/doctrine-module (1.0.0)
  - Removing doctrine/doctrine-orm-module (0.9.2)
  - Installing doctrine/doctrine-orm-module (0.5.6)

As far as I can see, for the DBAL you have marked v2.4.5 as [Latest release](https://github.com/doctrine/dbal/releases)

Additionaly, when I try to run `orm:schema-tool:update` from the CLI, I get an error:

>   [Symfony\Component\Console\Exception\CommandNotFoundException]
There are no commands defined in the "orm:schema-tool" namespace.

I checked and I have the `DoctrineModule` and `DoctrineORMModule` enabled, so it's not that.

**Comment by gianarb** [comment]
Hello @thexpand 
Thanks for this feedback, have you run `composer update` or `composer update doctrine/dbal`?

**Comment by thexpand** [comment]
Hi @gianarb 
I have run `composer update`.
Temporarily, I changed the version in _composer.json_ to `0.9.*`, so that I can update the schema, but obviously something is wrong.

**Comment by gianarb** [comment]
I am checking :)
Thanks

**Comment by gianarb** [comment]
Can I see your composer json?

**Comment by thexpand** [comment]
```json
{
	"minimum-stability": "stable",
	"name": "Rizn",
	"description": "Rizn",
	"license": "BSD-3-Clause",
	"keywords": [
		"rizn",
		"rizn"
	],
	"homepage": "http://rizn.bg/",
	"require": {
		"php": ">=5.3.3",
		"zendframework/zendframework": "2.*",
		"doctrine/doctrine-module": "*",
		"doctrine/doctrine-orm-module": "*",
		"zendframework/zend-developer-tools": "dev-master"
	},
	"autoload": {
		"psr-4": {
			"Rizn\\": "vendor/rizn/library/",
			"Application\\": "module/Application/"
		}
	}
}
```

**Comment by gianarb** [comment]
Can you try to remove 
```
"doctrine/doctrine-module": "*",
```
DoctrineORMModule manages itself its dependencies

**Comment by thexpand** [comment]
Thank you. It's twerking!
Oups.. working* :)
