### ISSUE TITLE
New release with DoctrineModule 1.0

### ISSUE THREAD

**Issue by Lansoweb** [doctrine/DoctrineORMModule#452]
Hi!
The doctrine-module 1.0 require is already merged on master (a day ago), any ETA for a release?
Thanks a lot for the hard work, great module!
Leandro Silva

**Comment by gianarb** [comment]
Hello

my idea is tag 1.0 for this module.. we are trying to understand the current situation.
if during this week we don't find a solution we will release 0.10.0 :)

**Comment by Lansoweb** [comment]
Great! Thanks!

**Comment by Lansoweb** [comment]
@gianarb I'm closing this now with the 0.10.0 release. Thanks!

**Comment by gianarb** [comment]
Thanks and sorry for the delay!

**Comment by Lansoweb** [comment]
@gianarb No problem, and thanks for the great work BTW :)
