### ISSUE TITLE
Lazy connection doesn't work

### ISSUE THREAD

**Issue by snapshotpl** [doctrine/DoctrineORMModule#454]
In my app, without any queries, connection is always created. I have found that https://github.com/doctrine/DoctrineORMModule/blob/5eacd0225a7a58e823018d0f22066885bb9416d6/src/DoctrineORMModule/Service/DBALConnectionFactory.php#L61 try to find out version and platform and it need connect do db to fetch this information. It's any way to cache or configure it?

**Comment by Ocramius** [comment]
@snapshotpl one way is to specify the version in the connection params. See also doctrine/DoctrineBundle#351

**Comment by snapshotpl** [comment]
Thanks! Works great I think we need to add this one to docs

**Comment by TomHAnderson** [comment]
@snapshotpl Please submit a PR to the docs. Thanks!
