### ISSUE TITLE
Inject DoctrineObject hydrator into Form/Fieldset

### ISSUE THREAD

**Issue by xelax90** [doctrine/DoctrineORMModule#456]
Hi,

when trying to solve some compatibility issues with ZF3 ServiceManager I have noticed that there is a factory for the `DoctrineModule\Stdlib\Hydrator\DoctrineObject` hydrator inside the HydratorManager. However I don't see any possibility to set the hydrator of a form or fieldset without using an initializer or providing a factory for it. Have a look at this example to illustrate what I mean:

I have defined an initializer for the `formElementManager` to inject an `ObjectManager` instance. This is how I wrote fieldsets until now:

``` php
namespace Application\Form;

use Zend\Form\Fieldset;
use DoctrineModule\Stdlib\Hydrator\DoctrineObject as DoctrineHydrator;
use DoctrineModule\Persistence\ObjectManagerAwareInterface;
use DoctrineModule\Persistence\ProvidesObjectManager;
use Application\Entity\Album;

class AlbumFieldset extends Fieldset implements ObjectManagerAwareInterface{
    use ProvidesObjectManager;

    public function init(){
        parent::init();
        $this->setHydrator(new DoctrineHydrator($this->getObjectManager()))
             ->setObject(new Album());

        //.... Field definition ....
    }
}
```

Then I could always just use this fieldset inside any form like this without any additional configuration:

``` php
namespace Application\Form;

use Zend\Form\Form;

class AlbumForm extends Form{
    public function init(){
        parent::init();

        $this->add(array(
            'name' => 'album',
            'type' => AlbumFieldset::class,
            'options' => array(
                'use_as_base_fieldset' => true,
            ),
        ));

        $this->add(array(
            'name' => 'submit',
            'type' => 'Submit',
        ));
    }
}
```

The obvious drawback of this is that I don't use the `HydratorManager` and the provided factory, although it seems to be the standard way according to the [ZF2 docs](http://framework.zend.com/manual/current/en/modules/zend.form.collections.html#creating-fieldsets).

One possible solution without an initializer would be the use of a factory like this:

``` php
use Interop\Container\ContainerInterface;
use Zend\ServiceManager\Factory\FactoryInterface;
use DoctrineModule\Stdlib\Hydrator\DoctrineObject as DoctrineHydrator;

class DoctrineHydratedFieldsetFactory implements FactoryInterface
{
    public function __invoke(ContainerInterface $container, $requestedName, array $options = null)
    {
        $hydratorManager = $container->get('HydratorManager');
        $doctrineHydrator = $hydratorManager->get(DoctrineHydrator::class);
        $fieldset = new $requestedName($options);
        $fieldset->setHydrator($doctrineHydrator);
        return $fieldset;
    }
}
```

The drawback of this is that I have to add a line in the configuration for each fieldset that I want to create like this, which can be a lot in a larger project. Would this be the correct solution for the ZF3 ServiceManager or is there any better way that I don't see? If this is the correct solution, I would recommend to add such a factory to this module and to adjust the docs for this.

**Comment by mpalourdio** [comment]
You could use an abstract factory to achieve this IMO.

**Comment by xelax90** [comment]
Yes, I thought about that. But wouldn't it be pretty much the same as the initializer approach? The abstract factory would be called for each created form element.

**Comment by DropdeadFredd** [comment]
Hi, I'm sorry if this is a stupid question (I'm new to ZF3 and Doctrine) but how do you make use of the DoctrineHydratedFieldsetFactory?
