### ISSUE TITLE
CLI silently dies with current zf2 2.5.3 and doctrine module 1.0 + orm 0.10.1

### ISSUE THREAD

**Issue by kevin-olbrich** [doctrine/DoctrineORMModule#461]
Hi,

I encountered a problem:

Sample Code:

```
        $em = $this->getServiceLocator()->get('doctrine.entitymanager.orm_default');

        echo "test1".PHP_EOL;

        $machines = $em->getRepository('Main\Entity\DataMachines')->findAll();

        echo "test2".PHP_EOL;
        die("die here...");
```

Output:

> C:\secret>php public\index.php my-cli-job
> 
> Deprecated: You are retrieving the service locator from within the class CronJobs\Controller\SecretController. Please be aware that ServiceLocatorAwareInterface is deprecated and will be removed in version 3.0, along with the ServiceLocatorAwareInitializer. You will need to update your class to accept all dependencies at creation, either via constructor arguments or setters, and use a factory to perform the injections. in C:\secret\vendor\zendframework\zend-mvc\src\Controller\AbstractController.php on line 258
> test1
> 
> C:\secret>

Maybe this is related to:
https://github.com/zendframework/zend-mvc/pull/88

The job silently dies when I call a function of doctrine.

Environment:

```
    "require": {
        "php": "^5.5 || ^7.0",
        "zendframework/zendframework": "^2.5.3",
        "zfcampus/zf-apigility": "~1.1",
        "zfcampus/zf-apigility-documentation": "^1.0.5",
        "zfcampus/zf-development-mode": "~2.0",
        "doctrine/doctrine-orm-module": "^0.10.0",
        "doctrine/doctrine-module": "^1.0.1",
        "doctrine/migrations": "dev-master",
        "swiftmailer/swiftmailer": "^5.4",
        "zfcampus/zf-apigility-doctrine": "^2.0",
        "bjyoungblood/bjy-authorize": "^1.4"
    },
```

**Comment by kevin-olbrich** [comment]
I found a solution to this problem. There was a colum I removed from the DB, my Entity had a property, getter & setter.
Maybe there is missing an exception?

**Comment by rochapablo** [comment]
+1

**Comment by TomHAnderson** [comment]
This is a ZF3 error which has been addressed in this module.
