### ISSUE TITLE
Call to a member function getName() on null in Zend Developer Tools

### ISSUE THREAD

**Issue by groseb** [doctrine/DoctrineORMModule#464]
![image](https://cloud.githubusercontent.com/assets/5783476/14779185/355fb474-0ad7-11e6-888d-78d0688c6922.png)

I managed to fix this by adding a simple not null check line 152 of the MetadataGrapher.php file : 

``` php
    /**
     * @param ClassMetadata $class1
     * @param ClassMetadata $class2
     * @return string|null
     */
    private function getClassReverseAssociationName(ClassMetadata $class1, ClassMetadata $class2)
    {
        foreach ($class2->getAssociationNames() as $class2Side) {
            $targetClass = $this->getClassByName($class2->getAssociationTargetClass($class2Side));
            if ($class1 !== null && $targetClass !== null && $class1->getName() === $targetClass->getName()) {
                return $class2Side;
            }
        }

        return null;
    }
```

I'm using ZDT 1.0.0-RC1, DoctrineModule 1.0.1 and DoctrineORMModule 0.10.0 but I tried and few other versions and still had the issue.

**Comment by TomHAnderson** [comment]
@groseb any change to this issue?

**Comment by groseb** [comment]
I haven't been using Zend Framework in a while now, I can't say

**Comment by FrankHouweling** [comment]
I have had the same issue today, due to a faulty classname in a relation (Camelcase instead of CamelCase). A null check is an option, but I would much prefer a clear Exception telling me what to look for. Is it OK if I submit a pull request?
