### ISSUE TITLE
Profiler for DoctrineCache and ZDT-Integration

### ISSUE THREAD

**Issue by Blaimi** [doctrine/DoctrineORMModule#466]
To get a better insight in what the doctrine-caches are doing, there should be a profiler for doctrine-caches and an entry in the zend-developer-toolbar.

As a quick&dirty-solution we implemented a module wich extends the original memcached-driver and a new cacheFactory which injects a DebugStack-like Logger to the caches we are using (metadata, query, result, hydration and some project-specific others to cache calculated values and proprietary annotations, the RBAC-tree, …). It’s working, but the solution is not very nice.

I want to start a discussion, about how to implement this in a scalable way. I’d like to see an extendable array in the configuration where to put the caches which are logged, preconfigured to the four orm_default caches.

The picture below shows our current implementation.
![zdt-chache](https://cloud.githubusercontent.com/assets/1222379/14880112/8452bc68-0d2d-11e6-829d-7592cc0f55a4.png)

**Comment by TomHAnderson** [comment]
@Blaimi for lack of discussion what would you like to do with this issue?

**Comment by Blaimi** [comment]
we are still using my q&d solution for our development. maybe I can find some time to create a clean solution when switching from zf2 to zf3 …

If no one else wants to contribute, you can close this issue and I'll request a reopen when needed.
