### ISSUE TITLE
How to extend Doctrine\ORM\EntityManager?

### ISSUE THREAD

**Issue by 27cm** [doctrine/DoctrineORMModule#467]
I would like to add some project usefull methods to EntityManager. Is it possible to use extended  `Doctrine\ORM\EntityManager` in Zend Framework projects?
```php
namespace Application\ORM;

use Doctrine\ORM\EntityManager as BaseEntityManager;

class EntityManager extends BaseEntityManager
{
    // ...
}
```

**Comment by 27cm** [comment]
The question is solved.

> You should never attempt to inherit from the EntityManager: Inheritance
> is not a valid extension point for the EntityManager. Instead you
> should take a look at the \Doctrine\ORM\Decorator\EntityManagerDecorator
> and wrap your entity manager in a decorator.

https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/EntityManager.php#L51-L54

**Comment by gianarb** [comment]
Thanks
