### ISSUE TITLE
What is the right way to use EntityManagerDecorator with DoctrineORMModule?

### ISSUE THREAD

**Issue by 27cm** [doctrine/DoctrineORMModule#468]
Try to explain the problem step by step:

1. I wrote `EntityManagerDecorator`:
    ```php
    namespace Application\ORM\Decorator;
    
    use Doctrine\ORM\Decorator\EntityManagerDecorator as BaseEntityManagerDecorator;
    
    class EntityManagerDecorator extends BaseEntityManagerDecorator
    {
        /**
         * @return Repository\UserRepository
         */
        public function getUserRepository()
        {
            return $this->getRepository('Application\Entity\User');
        }
    
        // Other methods...
    }
    ```

2. I found only one way to use the decorator - override the EntityManagerFactory:
    ```php
    namespace Application\ORM\Service;

    use Application\ORM\Decorator\EntityManagerDecorator;
    use DoctrineORMModule\Service\EntityManagerFactory as BaseEntityManagerFactory;
    use Zend\ServiceManager\ServiceLocatorInterface;

    class EntityManagerFactory extends BaseEntityManagerFactory
    {
        public function createService(ServiceLocatorInterface $serviceLocator)
        {
            $em = parent::createService($serviceLocator);
            $decorator = new EntityManagerDecorator($em);

            // ...

            return $decorator;
        }
    }
    ```

    Application module config:
    ```php
    return [
        'doctrine_factories' => [
            'entitymanager' => Application\ORM\Service\EntityManagerFactory::class,
        ],
        // ...
    ];
    ```

3. It works great, `$this->getServiceLocator()->get('Doctrine\ORM\EntityManager');` now returns my `EntityManagerDecorator`. But there is at least one problem - my custom `Repository\UserRepository` still using default `Doctrine\ORM\EntityManager` instead of `EntityManagerDecorator`. So I had to override `getRepository()`:
    ```php
    use Doctrine\ORM\EntityRepository;

    abstract class AbstractEntityRepository extends EntityRepository
    {
        public function setEntityManager(EntityManagerInterface $entityManager)
        {
            $this->_em = $entityManager;
            return $this;
        }
    }

    class UserRepository extends AbstractEntityRepository
    {
        // Some methods, using EntityManagerDecorator...
    }

    class EntityManagerDecorator extends BaseEntityManagerDecorator
    {
        public function getRepository($className)
        {
            $repository = parent::getRepository($className);
            if ($repository instanceof AbstractEntityRepository) {
                $repository->setEntityManager($this);
            }
            return $repository;
        }

        // Other methods...
    }
    ```

Is it the right way to use `EntityManagerDecorator` with `DoctrineORMModule`?

**Comment by Ocramius** [comment]
A couple things:

 1. don't extend the EntityManager, please. Use the [`EntityManagerInterface`](https://github.com/doctrine/doctrine2/blob/59a041095183f188faac6bc784074f4f88475a4a/lib/Doctrine/ORM/EntityManagerInterface.php) instead
 2. simply define following config:

    ```php
    return [
        'service_manager' => [
            'factories' => [
                'doctrine.entitymanager.orm_default' => MyFactory::class,
            ],
        ],
    ];
    ```

As for the logic above (if I understand it correctly, that's the reason you needed to extend the EntityManager), you can just use the [`RepositoryFactory`](https://github.com/doctrine/doctrine2/blob/59a041095183f188faac6bc784074f4f88475a4a/lib/Doctrine/ORM/Configuration.php#L799-L821) for that instead.

**Comment by 27cm** [comment]
@Ocramius, I didn't extend the EntityManager. I tried to follow [this note](https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/EntityManager.php#L51-L54) and use decorator. I don't understand where should I use `EntityManagerInterface`?

**Comment by Ocramius** [comment]
`EntityManagerInterface` can be used in place of any `EntityManager`. I indeed misread what you did before, sorry.

**Comment by kusmierz** [comment]
@Ocramius, so what is "the right way" to use EntityManagerDecorator? In particular I'm interesting to have my EM in repositories...

**Comment by TomHAnderson** [comment]
http://blog.tomhanderson.com/2016/01/dependency-injection-in-doctrine.html

**Comment by Ocramius** [comment]
@kusmierz IMO, "the right way" is to NOT use the `EntityManagerDecorator`. It was designed before doctrine2 had any `EntityManagerInterface`, and implementing your own `getRepository` API is sufficient.
