### ISSUE TITLE
Problem caching modules

### ISSUE THREAD

**Issue by guilherme90** [doctrine/DoctrineORMModule#469]
Hello, how are you? I'm products to perform cache modules.

When I enable the cache ZF2, the following message appears: 

```
Fatal error: Call to undefined method DoctrineORMModule \ Service \ EntityManagerFactory :: __ set_state () in C: \ xampp \ htdocs \ www \ site \ portal \ data \ cache \ module-config- cache.php on line 320
```

From what I researched, this means that anonymous functions can not be cached. And this occurs only with DoctrineORMModule. Can you tell me why this is happening? I looked in the core and did not find anything related to anonymous function, but factories, what is the right thing to do.

If you want to see my settings [here are](https://gist.github.com/guilherme90/46b0ddca17da718a2de65291e8465c2c).

Thanks.

**Comment by Ocramius** [comment]
can you provide a trace for the error?

**Comment by guilherme90** [comment]
Look, I do not know if this can help you, but take a look in my file that generated by the [module cache](https://gist.github.com/guilherme90/eebca4731d82f2fae2345a8a969d9202).

I do not know if I can track. I just enable the cache application.config, and ran my application. And to run my app, this error is thrown.

**Comment by Ocramius** [comment]
No, that is not useful: I'd need a stack trace to know which component causes the failure.

**Comment by guilherme90** [comment]
Understood. Wait until you will return soon

**Comment by guilherme90** [comment]
@Ocramius See the print failure

![debug](https://cloud.githubusercontent.com/assets/2879939/15368559/c5f398a4-1d04-11e6-906f-4cb8d6ffb35b.png)

**Comment by Ocramius** [comment]
Yes, this looks like somebody put an actual `EntityManagerFactory` instance in your configuration, then the config got serialized and the app crashes at un-serialization.

Check your configs, making sure only scalar values are in there (no object instances)

**Comment by guilherme90** [comment]
Only place that has real instance of `EntityManagerFactory` is in my doctrine configuration file.
Just a question. Not if it has error fault, but to confirm. If in my factory, I do `$entityManager = $serviceLocator->get('doctrine.entitymanager.em_default');` I do can be a cause of this error?

**Comment by Ocramius** [comment]
>  I do can be a cause of this error?

I doubt that this is related to the error: this happens much before it is even attempted to fetch the `EntityManager` anywhere in your app

**Comment by guilherme90** [comment]
Understood. I really can not see why that happens. Do you have any more ideas? Anyway, thank you very much for your help.

**Comment by Ocramius** [comment]
@guilherme90 can you show the gist of that file again? Seems that it was deleted.

**Comment by guilherme90** [comment]
[doctrine.config.php](https://gist.github.com/guilherme90/3df561709ef262043e424bc74f638857)

[module-config-cache.php](https://gist.github.com/guilherme90/b0f56af37e2613ab829dab75a358c835)

**Comment by CentaurWarchief** [comment]
@guilherme90 isn't there a typo? https://gist.github.com/guilherme90/3df561709ef262043e424bc74f638857#file-doctrine-config-php-L24 `facories`

**Comment by guilherme90** [comment]
Yes, it was however corrected the error persists.

**Comment by Ocramius** [comment]
[these](https://gist.github.com/guilherme90/3df561709ef262043e424bc74f638857#file-doctrine-config-php-L25-L27) should indeed not be in the main module config. The shouldn't actually be needed at all

**Comment by guilherme90** [comment]
Hello @Ocramius . Thanks a lot for the help! You're right, those lines were totally unnecessary and I do not I realized this detail!

Thank you very much for your efforts to help me, big hug!

**Comment by Ocramius** [comment]
Closing then :-)
