### ISSUE TITLE
0.11.0 incompatible with ZF3 Expressive Application

### ISSUE THREAD

**Issue by chriskl** [doctrine/DoctrineORMModule#480]
Hi,

When I do `composer require doctrine/doctrine-orm-module` using the Zend Expressive skeleton, that has been 'composer update'd, I get this:

`
Using version ^0.11.0 for doctrine/doctrine-orm-module
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/doctrine-orm-module ^0.11.0 -> satisfiable by doctrine/doctrine-orm-module[0.11.0].
    - doctrine/doctrine-orm-module 0.11.0 requires zendframework/zend-hydrator ^1.1 -> satisfiable by zendframework/zend-hydrator[1.1.0, 1.1.x-dev] but these conflict with your requirements or minimum-stability.
`

I appear to have zend-hydrator 2.2.1 installed...

**Comment by svycka** [comment]
zend-hydrator ^2.0 is not supported yet, it would be BC break. also zend-mvc 3.0 is not supported for those we have to drop zend-mvc 2.0, zend-stdlib 2.0 and zend-hydrator 1.0 support. If I did not forget something.

**Comment by gianarb** [comment]
The plan is tag 1.0.0 for DoctrineORMModule soon.. Like this week.. and start to work to support only ZF 3.0..

**Comment by chriskl** [comment]
Anything I can do to help - I'm working on a ZE ZF3 app w/ doctrine at the moment...

**Comment by gianarb** [comment]
Well there are a big PR to review 
https://github.com/doctrine/DoctrineORMModule/pull/479/files

You can try to use this branch on your project.. :) 
Thanks a lot
