### ISSUE TITLE
Is there a reason why we don't have version 1.0?

### ISSUE THREAD

**Issue by svycka** [doctrine/DoctrineORMModule#481]
If we follow http://semver.org/ (I guess not) 0.x versions can be released with BC breaks so I have set version in composer ^0.9 then ^0.10 and ^0.11 a bit annoying when it changes. The project has  stable API and 1.0 could be released long ago. 

Maybe if we do not follow semver versioning then add this in readme that it is save to have 0.* in composer and will not have any BC breaks in 0.x versions.

as we don't have BC changes in 0.x releases maybe worth to add info how this module decides on version numbers? Some early releases had BC breaks I guess so I don't feel comfortable having 0.* in composer.

**Comment by gianarb** [comment]
Hello @svycka my plan was just wait few days to catch some feedback about the last release.. All seems quite and I will release 1.0.0 soon.. I think this week.

Thanks!
