### ISSUE TITLE
1.0.0 incompatible with ZF3

### ISSUE THREAD

**Issue by GoDoY-SP-** [doctrine/DoctrineORMModule#487]
Hi,

When I do composer require doctrine/doctrine-orm-module using the Zend Framework 3 skeleton, that has been 'composer update'd, I get this:

Using version ^1.0 for doctrine/doctrine-orm-module
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/doctrine-orm-module ^1.0 -> satisfiable by doctrine/doctrine-orm-module[1.0.0].
    - doctrine/doctrine-orm-module 1.0.0 requires zendframework/zend-mvc ^2.5.2 -> satisfiable by zendframework/zend-mvc[2.5.2, 2.5.3, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.7.0, 2.7.1, 2.7.10, 2.7.2, 2.7.3, 2.7.4, 2.7.5, 2.7.6, 2.7.7, 2.7.8, 2.7.9] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

**Comment by niklasschaeffer** [comment]
You will have to wait until there is an official release for Zf 3.0. Until now just don't upgrade your applications since Zf 3.0 is not out for so long.

**Comment by gianarb** [comment]
We can not support zend mvc 3.0 without introduce BC. We are working on DoctrineORMModule 2.0 that will support only ZF3.

Thanks for you notification #479
