### ISSUE TITLE
Error: The option "query_cache" does not have a callable "setQueryCache"

### ISSUE THREAD

**Issue by aimfeld** [doctrine/DoctrineORMModule#490]
I have been following [this tutorial](https://github.com/doctrine/DoctrineORMModule/blob/master/docs/cache.md#example-with-redis) to set up doctrine redis caching using the ZF2 DoctrineORMModule (version 1.0.0).

However, I get the following error:

```
Fatal error: Uncaught Zend\Stdlib\Exception\BadMethodCallException: 
The option "query_cache" does not have a callable 
"setQueryCache" ("setquerycache") setter method which must be defined in ...
```

Might this be bug or am I missing some configuration settings not mentioned in the tutorial?

**Comment by aimfeld** [comment]
I have tried several methods, including the one [here](http://stackoverflow.com/a/38626865/94289), but I still get the same error message. I think it might be a bug in DoctrineORMModule.

**Comment by TomHAnderson** [comment]
Does this issue help?  https://github.com/doctrine/DoctrineORMModule/issues/523

**Comment by aimfeld** [comment]
I noticed a bug in my configuration, I had placed my second level cache configuration under `doctrine->connection->orm_default` instead of `doctrine->configuration->orm_default`. I think this was the cause of the error.
