### ISSUE TITLE
No matching Package Found for dev-master

### ISSUE THREAD

**Issue by axelcho** [doctrine/DoctrineORMModule#495]
I got the following errors since about 2 hours ago.

    - doctrine/doctrine-orm-module dev-master requires doctrine/doctrine-module dev-feature/zf3compat -> no matching package found.
    - doctrine/doctrine-orm-module dev-master requires doctrine/doctrine-module dev-feature/zf3compat -> no matching package found.
    - Installation request for doctrine/doctrine-orm-module dev-master -> satisfiable by doctrine/doctrine-orm-module[dev-master].

**Comment by axelcho** [comment]
I think the feature branch pointed for doctrine-module is now merged.

https://github.com/doctrine/DoctrineModule/pull/567

It happened about 5 hours ago. 

So the requirement should be updated at DoctrineOrmModule too.

**Comment by axelcho** [comment]
https://github.com/doctrine/DoctrineORMModule/pull/494 resolved this issue.

**Comment by gianarb** [comment]
Anyway if you are working on a stable product my suggestion is use a tag and not dev-master.. right now i can only mark like stable our releases.. Not master branch.

Thanks
