### ISSUE TITLE
1.0.0 "It is compatible with ZF2 and ZF3"

### ISSUE THREAD

**Issue by wtabata** [doctrine/DoctrineORMModule#499]
Problem 1
    - Installation request for doctrine/doctrine-orm-module 1.0.0 -> satisfiable by doctrine/doctrine-orm-module[1.0.0].
    - doctrine/doctrine-orm-module 1.0.0 requires zendframework/zend-mvc ^2.5.2 -> satisfiable by zendframework/zend-mvc[2.5.2, 2.5.3, 2.6.0, 2.6.1, 2.6.                                               2, 2.6.3, 2.7.0, 2.7.1, 2.7.10, 2.7.2, 2.7.3, 2.7.4, 2.7.5, 2.7.6, 2.7.7, 2.7.8, 2.7.9] but these conflict with your requirements or minimum-stability.

;( it`s not

**Comment by kokspflanze** [comment]
you can use ```
"doctrine/doctrine-orm-module": "dev-master as 1.0.9",
"doctrine/doctrine-module": "dev-master",
```

unt its not released

**Comment by wtabata** [comment]
tks man!
