### ISSUE TITLE
doctrine/doctrine-orm-module" : "dev-master"

### ISSUE THREAD

**Issue by waney** [doctrine/DoctrineORMModule#501]
[Sun Aug 28 15:40:21.056869 2016] [:error] [pid 7949:tid 139695723886336] [client 127.0.0.1:40974] PHP Fatal error:  Uncaught Doctrine\\Common\\Persistence\\Mapping\\MappingException: The class '' was not found in the chain configured namespaces Base\\Entity, Acl\\Entity, Api\\Entity, User\\Entity, Company\\Entity, GEM\\Entity, Jewelry\\Entity, Inventory\\Entity, Sale\\Entity, Funds\\Entity, WeChat\\Entity, Warehouse\\Entity, Supplier\\Entity, Customer\\Entity, Purchase\\Entity, TeaWare\\Entity, ReportCheck\\Entity, FileService\\Entity, PDF\\Entity in /Data/abc/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/MappingException.php:37\nStack trace:\n#0 /Data/abc/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/MappingDriverChain.php(112): Doctrine\\Common\\Persistence\\Mapping\\MappingException::classNotFoundInNamespaces(false, Array)\n#1 /Data/abc/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(151): Doctrine\\Common\\Persistence\\Mapping\\Driver\\MappingDriverChain->loadMetadataForClass(false, Object(Doctrine\\ORM\\Mapping\\ClassMetadata))\n#2 /Data/abc/v in /Data/abc/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/MappingException.php on line 37, referer: http://www.abc.cn/customer/list

**Comment by Ocramius** [comment]
Not a bug, but misuse. Possibly caused by `get_class($nonObject)`, causing `get_class()` to fail and return `false`.

For sure not an issue of this repository.

**Comment by Ocramius** [comment]
Not a bug, but misuse. Possibly caused by `get_class($nonObject)`, causing `get_class()` to fail and return `false`.

For sure not an issue of this repository.

Please do check your stack trace: I can clearly see a `false` there, while it should be a class name.
