### ISSUE TITLE
Where to handle schema filter configuration?

### ISSUE THREAD

**Issue by clemf** [doctrine/DoctrineORMModule#502]
I'm trying to filter out some custom tables from the schema tool so that I can use migrations. The doctrine documentation mention that the bundle for Symfony has a config option for this, does this have one as well?

http://doctrine-orm.readthedocs.io/projects/doctrine-migrations/en/latest/reference/generating_migrations.html#ignoring-custom-tables

http://symfony.com/doc/current/bundles/DoctrineMigrationsBundle/index.html#manual-tables

**Comment by clemf** [comment]
I figured out that this is supported in the command line tool using the `filter-expression`. So using this command would filter out all tables starting with `foobar`:
```
vendor/bin/doctrine-module migrations:diff --filter-expression='~^(?!foobar)~'
```
Still, it would be nice to be able to set in in a configuration file like Symfony.

**Comment by thomasvargiu** [comment]
You can put a file called `migrations-input.php` in the root directory of your project with something like this:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$input = new \Symfony\Component\Console\Input\ArgvInput();

$filterExpression = $input->getArgument('filter-expression');

if (!$filterExpression) {
    $input->setArgument('filter-expression', '/^prefix_/');
}

return $input;
```

**Comment by fritz-gerneth** [comment]
Having had the same issue I looked into on how this can be achieved in a cleaner way. The changes required to add this external are quite small, yet I think this should be something included in here too.

Doing this as an extension is quite easy and requires to overwrite the `Configuration` and `ConfigurationFactory` classes:

1) Extending the Configuration class
```php
class Configuration extends \DoctrineORMModule\Options\Configuration
{
    protected $schemaFilter;

    public function setSchemaFilter($schemaFilter)
    {
        $this->schemaFilter = $schemaFilter;
    }

    public function getSchemaFilter()
    {
        return $this->schemaFilter;
    }
}
```

2) Extending the `ConfigurationFactory`
```php
class ConfigurationFactory extends \DoctrineORMModule\Service\ConfigurationFactory
{
    /**
     * {@inheritDoc}
     */
    public function __invoke(ContainerInterface $container, $requestedName, array $createOptions = null)
    {
        $config = parent::__invoke($container, $requestedName, $createOptions);

        /** @var $options Configuration */
        $options = $this->getOptions($container);
        $schemaFilter = $options->getSchemaFilter();

        if (!empty($schemaFilter)) {
            $config->setFilterSchemaAssetsExpression($options->getSchemaFilter());
        }

        return $config;
    }

    public function getOptionsClass()
    {
        return Configuration::class;
    }
}
```

3) Telling the module to load the Configuration from our own Factory (this ends up in the `module.config.php` or any other config file)
```php
return [
    'doctrine_factories' => [
        'configuration' => ConfigurationFactory::class,
    ],
];
```

4) Configure the schema-filter as part of the existing configuration for this module:
```
php
return [
    'doctrine' => [
        'configuration' => [
            'orm_default' => [
                'schema_filter' => '~^(?!t_)~',
            ],
        ],
];
```

This seems to be the proper way of handling this. Should also be compatible with working with multiple entity managers and keeps the configuration of this where it belongs to.

**Comment by bcremer** [comment]
Just a heads up that this was implemeted in https://github.com/doctrine/DoctrineORMModule/pull/527 as part of the 1.1.4 release.
