### ISSUE TITLE
“No Metadata Classes to process”  In zf3 + orm:schema-tool:create

### ISSUE THREAD

**Issue by sathyashrayan** [doctrine/DoctrineORMModule#503]
I have installed two instance of zf2 and zf3 with vhost. For zf3 I have Installed the development version of doctrine with the composer.json as per the instruction given in this link 

https://github.com/doctrine/DoctrineORMModule/issues/491

And for zf2 it's a normal installation. 

Both the developer tools shows the Dependency graph correctly

But in zf3 when I use 

orm:schema-tool:create 

Its always showing No Metadata Classes to process. I have attached the relevant screenshot to support. 

I know doctrine yet to support zf3. I just want some guide to look into the issue if it's not beyond my understanding.

![zf3_3](https://cloud.githubusercontent.com/assets/4995301/18580030/c42a41d2-7c16-11e6-85d7-c198c48a2715.png)
![zf2_3](https://cloud.githubusercontent.com/assets/4995301/18580031/c4334eee-7c16-11e6-8c6f-7a6642e85a76.png)
![zf3_2](https://cloud.githubusercontent.com/assets/4995301/18580032/c43ed566-7c16-11e6-9d4f-79a44be24217.png)
![zf2_2](https://cloud.githubusercontent.com/assets/4995301/18580033/c4439e7a-7c16-11e6-98ba-6239645b1c0e.png)
![zf3_1](https://cloud.githubusercontent.com/assets/4995301/18580034/c44cbb36-7c16-11e6-8aa7-c4ed6108c435.png)
![zf2_1](https://cloud.githubusercontent.com/assets/4995301/18580037/c54da6d0-7c16-11e6-857d-8835d3b8776d.png)

**Comment by TomHAnderson** [comment]
Dump your config and ensure your doctrine configuration is correct for your metadata paths.

**Comment by TomHAnderson** [comment]
Closing for lack of feedback.

**Comment by zeleniy** [comment]
![screenshot from 2019-01-29 16-01-37](https://user-images.githubusercontent.com/2780617/51910101-47c0af00-23df-11e9-9790-3827a47be6fc.png)

**Comment by Ocramius** [comment]
@zeleniy once you exported the data to somewhere, you still need to configure the metadata drivers to read mappings from that location.

Meanwhile, locking here: discussion was already previously resolved.
