### ISSUE TITLE
Interface proxy is not created

### ISSUE THREAD

**Issue by guru888** [doctrine/DoctrineORMModule#511]
Hi, I want to speed up my application. So I have installed APC with doctrine2 - ZF2. Caching is working fine. Proxies are generated for all the entities. But I have one interface under entities, the proxy for this interface is not created. So it is throwing a mapping error. Any idea how to resolve this issue.

**Comment by Ocramius** [comment]
Proxies are only generated once per class metadata, not for interfaces.
Consider writing a more complete bug report, as the current information is
insufficient for us to help you.

**Comment by guru888** [comment]
Fatal error: Doctrine\Common\Persistence\Mapping\MappingException: Class 'WdwTask\Entity\TaskUserInterface' does not exist in /Applications/XAMPP/xamppfiles/htdocs/TMS2/vendor/zendframework/zend-view/src/Helper/Navigation/AbstractHelper.php on line 153
Call Stack
#	Time	Memory	Function	Location
1	0.0002	245376	{main}( )	../index.php:0
2	0.3388	25720384	Zend\Mvc\Application->run( )	../index.php:33
3	1.9097	38467720	Zend\Mvc\Application->completeRequest( )	../Application.php:356
4	1.9097	38467720	Zend\EventManager\EventManager->triggerEvent( )	../Application.php:384
5	1.9097	38467720	Zend\EventManager\EventManager->triggerListeners( )	../EventManager.php:251
6	1.9098	38469528	call_user_func:{/Applications/XAMPP/xamppfiles/htdocs/TMS2/vendor/zendframework/zend-eventmanager/src/EventManager.php:490} ( )	../EventManager.php:490
7	1.9098	38469912	Zend\Mvc\View\Http\DefaultRenderingStrategy->render( )	../EventManager.php:490
8	1.9098	38470448	Zend\View\View->render( )	../DefaultRenderingStrategy.php:105
9	1.9145	38516064	Zend\View\Renderer\PhpRenderer->render( )	../View.php:207
10	1.9148	38552504	include( '/Applications/XAMPP/xamppfiles/htdocs/TMS2/vendor/wdw/application/view/layout/layout.phtml' )	../PhpRenderer.php:502
11	2.0911	41711184	Zend\View\Renderer\PhpRenderer->render( )	../layout.phtml:29
12	2.0913	41737632	include( '/Applications/XAMPP/xamppfiles/htdocs/TMS2/vendor/wdw/application/view/layout/blocks/sidebar.phtml' )	../PhpRenderer.php:502
13	2.0955	41995168	Zend\View\Helper\Navigation\AbstractHelper->__toString( )	../PhpRenderer.php:24
14	2.1280	42164160	trigger_error ( )	../AbstractHelper.php:153

**Comment by Ocramius** [comment]
Possibly missing class on one of the type hints in a certain class for which proxying is attempted. The trace is incomplete (missing previous errors/exceptions)

**Comment by guru888** [comment]
Basically it is not a class it's an interface.

**Comment by Ocramius** [comment]
@guru888 first gut feeling is that you have:

```php
class MyEntity
{
    public function something(TheInterface $interface) {} // it fails while reflecting this
}
```

**Comment by guru888** [comment]
namespace WdwTask\Entity;

use DateTime;

interface TaskUserInterface
{
    /**
     * Get id
     *
     * @return integer
     */
    public function getId();

    /**
     * Get email
     *
     * @return string
     */
    public function getEmail();
.....

**Comment by Ocramius** [comment]
Most probably fails to autoload it (permissions, maybe?)

**Comment by guru888** [comment]
I don't think it's permission issue. I have attached ls -l result over here
-rw-rw-rw-  1 root  admin   1149 19 Aug 15:37 TaskScheduleReport.php
-rw-rw-rw-  1 root  admin   1623 19 Aug 15:37 TaskSilence.php
-rw-r--r--  1 guru  admin   4348 22 Nov 10:38 TaskTime.php
-rw-rw-rw-  1 guru  admin   4301  5 Dec 09:51 TaskUserInterface.php

**Comment by Ocramius** [comment]
Yes, but it is clear that it can't autoload it (if you dump previous exceptions, you will see a "class not found" exception thrown as `ReflectionException`.

Also, the fact that you have different users and access levels there smells (a lot!).

The bug is indeed on your side of the fence, sorry.

If it ends up being on doctrine's side, please feel free to ping again and I'll reopen, but I'm closing now.
