### ISSUE TITLE
[Question] Does this package includes data-fixtures?

### ISSUE THREAD

**Issue by chris-fa** [doctrine/DoctrineORMModule#512]
I'm looking for docs regarding this module integrated with `doctrine/data-fixtures`, similar to the integration it has with `doctrine/migrations`, but I am unable to find  docs on it.

Does this module includes data-fixtures too or do I have to use a dedicated one like [Hounddog's](https://github.com/Hounddog/DoctrineDataFixtureModule) ?

**Comment by TomHAnderson** [comment]
I strongly and with bias recommend https://github.com/API-Skeletons/zf-doctrine-data-fixture
