### ISSUE TITLE
Does this module supports APCu?

### ISSUE THREAD

**Issue by chris-fa** [doctrine/DoctrineORMModule#513]
I'm reading through the module configuration cache file that generates ZF2, and I read the following line:

```
      'apcu' => 
      array (
        'class' => 'Doctrine\\Common\\Cache\\ApcuCache',
        'namespace' => 'DoctrineModule',
      ),
```

Which makes me think (even if the docs doesn't explicitly specify), if I do on `config/autoload/global.php`:

```
    'configuration' => [
      'orm_default' => [
        'metadata_cache'  => 'apcu',
      ],
    ],
```

It should work. However, after reloading the page and running `vendor/bin/doctrine-module orm:clear-cache:metadata` I get:

```
Clearing ALL Metadata cache entries
No cache entries were deleted.
```

So I'm now wondering if I'm actually wrong, or do I have to configure it manually on my project?

**Comment by tommyseus** [comment]
It isn't possible to delete the APCU Cache from the Webserver on CLI.

The command (Doctrine\ORM\Tools\Console\Command\ClearCache\MetadataCommand) should throw an exception for apcu (like apc and xcache): "Cannot clear APCU Cache from Console, its shared in the Webserver memory and not accessible from the CLI."

**Comment by TomHAnderson** [comment]
@tommyseus Would you put in a PR for your solution?

**Comment by tommyseus** [comment]
PR created: doctrine/doctrine2#6498

**Comment by Ocramius** [comment]
Closing here as per doctrine/doctrine2#6498. Thanks @tommyseus!
