### ISSUE TITLE
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'username'@'localhost' (using password: YES) in /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43

### ISSUE THREAD

**Issue by andrewizotov** [doctrine/DoctrineORMModule#514]
Hello Guys, please help with it . I use console application.
Seems to be Doctrin module  read a config file  from "my_app/vendor/doctrine/doctrine-orm-module/config/module.config.php"
Not mine , which is located in my_appp/config/application.config.php , here it is my configuration for database connection . 
`'doctrine' => [
        'connection' => [
            'orm_default' => [
                'driverClass' => 'Doctrine\DBAL\Driver\PDOMySql\Driver',
                'params' => [........]`
any idea ?
![image](https://cloud.githubusercontent.com/assets/17500052/21482116/8b9e4014-cb78-11e6-8c25-7b0795b8e62a.png)

Thanks .

**Comment by xelax90** [comment]
You should put your config file into the config/autoload folder or it won't be loaded into your application (see https://github.com/zendframework/ZendSkeletonApplication/tree/master/config/autoload). Also you should use the .global.php or .local.php suffix. I would recommend .local.php to prevent your username and password from being accidentally pushed into your git repository

**Comment by andrewizotov** [comment]
Thanks @xelax90 , it works correctly :)
