### ISSUE TITLE
Sharing a Memcache/Redis server between projects.

### ISSUE THREAD

**Issue by MIHDashboard** [doctrine/DoctrineORMModule#523]
Hi,

How would one share a caching server between multiple projects?

I've set a namespace, lets call it testns, but it does not get used by entity and query cache.

See example keys:
application_entity_user[application_entity_user_233e943aa5b5c06331de48659a217b66964a293f]
query_cache_region[query_cache_region_005247c9d46dd190ca5cb657913749b47bbde7b9]
testns[613-1-72016-02-23]

My config is:
```
'doctrine.cache.redis' => function ($sm) {
            $cache = new \Doctrine\Common\Cache\RedisCache();
            $redis = new \Redis();

            $redis->connect(
                localhost,
                6379
            );
            $cache->setRedis($redis);
            $cache->setNamespace('testns');

            return $cache;
        }
```

Any help would be much appreciated. Thanks.

Regards.
JJ

**Comment by MatthiasKuehneEllerhold** [comment]
You have to set the namespace in the cache-configuration of doctrine (e. g. your application.config.php or module.config.php):
doctrine => cache => doctrine.cache.redis => namespace => 'testns'

**Comment by MIHDashboard** [comment]
Hi,

Thanks for the quick response! In my module.config.php I've added:

```
'doctrine' => array(
  'driver' => array(
            'configuration' => array(
                'orm_default' => array(
                    'query_cache'      => 'redis',
                'result_cache'     => 'redis',
                'metadata_cache'   => 'redis',
                'hydration_cache'  => 'redis',
                )
            ),
            'my_annotation_driver' => array(
                'class' => 'Doctrine\ORM\Mapping\Driver\AnnotationDriver',
                'cache' => 'array',
                'paths' => array(
                    __DIR__ . '/../src/Application/Entity'
                ),
            ),
            'orm_default' => array(
                'drivers' => array(
                    'Application\Entity' => 'my_annotation_driver',
                ),
            ),
            __NAMESPACE__ => array(
                'cache' => 'redis',
            ),
        ),
        'cache' => array(
            'redis' => array(
                'namespace' => 'testns',
            ),
        ),
)
```

No luck though. I'll debug the vendor code and see if I can find out where it is going wrong.

Thanks.
JJ

**Comment by MIHDashboard** [comment]
I can't have two 'my_annotation_driver' keys in that array? Like this? 

```
    'driver' => array(
            'configuration' => array(
                'orm_default' => array(
                    'query_cache'      => 'redis',
                    'result_cache'     => 'redis',
                    'metadata_cache'   => 'redis',
                    'hydration_cache'  => 'redis',
                )
            ),
            'my_annotation_driver' => array(
                'class' => 'Doctrine\ORM\Mapping\Driver\AnnotationDriver',
                'cache' => 'redis',
                'paths' => array(
                    __DIR__ . '/../src/Application/Entity'
                ),
            ),
            'orm_default' => array(
                'drivers' => array(
                    'Application\Entity' => 'my_annotation_driver',
                ),
            ),
        ),
        'cache' => array(
            'redis' => array(
                'namespace' => 'testns',
            ),
        ),
        'fixture' => array(
            'fixtures' => __DIR__ . '/../src/Application/Fixture',
        )
    ),
```

**Comment by MatthiasKuehneEllerhold** [comment]
Oh sorry, you're right! The last version of your config should be correct IMHO.

**Comment by jarrettj** [comment]
Thanks for the help, but no luck.

The scenario is, I have a test/prod deployment sharing redis. They have shared it for years. I just set the namespace as in my original post, using $cache->setNamespace().

After a recent deploy, about a week ago, the caching issues started happening. I assumed its a namespace issue. As it is returning the same entities for both test/prod.

On a side note, I have second level cache enabled. It caches every entity. This always worked though. I never had an issue like this before. I'll just disable it on prod for the meantime.

Will continue trying to step through code to figure out what has changed. If anything.

Thanks for the help @MatthiasKuehneEllerhold.

Regards.
JJ
