### ISSUE TITLE
ZF3 development mode disable : Call to undefined method DoctrineORMModule\Service\DBALConnectionFactory::__set_state()

### ISSUE THREAD

**Issue by fandria** [doctrine/DoctrineORMModule#535]
Using the development mode in ZF3 it works well, but while disabling the development mode I get the following issue.
`
Fatal error: Uncaught Error: Call to undefined method DoctrineORMModule\Service\DBALConnectionFactory::__set_state() in /var/www/app/data/cache/modulecache/module-config-cache.application.config.cache.php:3220 Stack trace: #0 /var/www/app/vendor/zendframework/zend-modulemanager/src/Listener/ConfigListener.php(392): include() #1 /var/www/app/vendor/zendframework/zend-modulemanager/src/Listener/ConfigListener.php(70): Zend\ModuleManager\Listener\ConfigListener->getCachedConfig() #2 /var/www/app/vendor/zendframework/zend-modulemanager/src/Listener/DefaultListenerAggregate.php(112): Zend\ModuleManager\Listener\ConfigListener->__construct(Object(Zend\ModuleManager\Listener\ListenerOptions)) #3 /var/www/app/vendor/zendframework/zend-modulemanager/src/Listener/DefaultListenerAggregate.php(42): Zend\ModuleManager\Listener\DefaultListenerAggregate->getConfigListener() #4 /var/www/app/vendor/zendframework/zend-mvc/src/Service/ModuleManagerFactory.php(77): Zend\ModuleManager\Listener\DefaultListenerAggregate->attach(Object(Zend\Even in /var/www/app/data/cache/modulecache/module-config-cache.application.config.cache.php on line 3220`

It seems like cache files are not well formated.

I use several entities managers to handle several databases connections.

Here is my factory for the other entity manager :
`
'factories' => [
        'doctrine.connection.orm_newdle'           => new \DoctrineORMModule\Service\DBALConnectionFactory('orm_newdle'),
        'doctrine.configuration.orm_newdle'        => new \DoctrineORMModule\Service\ConfigurationFactory('orm_newdle'),
        'doctrine.entitymanager.orm_newdle'        => new \DoctrineORMModule\Service\EntityManagerFactory('orm_newdle'),
        'doctrine.driver.orm_newdle'               => new \DoctrineModule\Service\DriverFactory('orm_newdle'),
        'doctrine.eventmanager.orm_newdle'         => new \DoctrineModule\Service\EventManagerFactory('orm_newdle'),
        'doctrine.entity_resolver.orm_newdle'      => new \DoctrineORMModule\Service\EntityResolverFactory('orm_newdle'),
        'doctrine.sql_logger_collector.orm_newdle' => new \DoctrineORMModule\Service\SQLLoggerCollectorFactory('orm_newdle'),
    ],
`

**Comment by Ocramius** [comment]
You can't store objects in the configuration without causing this, since `var_export()` will always produce `__set_state()` calls in the generated code

**Comment by fandria** [comment]
Yeah this was my fault.
I was putting the factories in my module.config.php file instead my Module.php file.
That fixes this.
Thank you for the tips

**Comment by MatthiasKuehneEllerhold** [comment]
You could also implement the __set_state() function in order to keep using the factories.
For example:
```
public static function __set_state($data)
{
    return new self($data['parameter']);
}
```

**Comment by Ocramius** [comment]
@MatthiasKuehneEllerhold won't be done in this module though. Relying on `__set_state()` is generally a bad idea :|

**Comment by MatthiasKuehneEllerhold** [comment]
Sorry if I'm taking over this issue and I know its totally off-limits from Doctrine but now I'm curious:

I've got a few general factories that just take a simple configuration key in order to provide the almost same factory for different objects. I figured a reusable factory with a string in its constructor would be a good way?

The factory looks like this (stripped out comments, auxiliary code, etc...):
```
class FmRepositoryFactory implements FactoryInterface
{
    protected $connection;

    public function __construct(string $connection)
    {
        $this->connection = $connection;
    }

    public function __invoke(
        ContainerInterface $container,
        $requestedName,
        array $options = null
    ): AbstractFmRepository {
        return new $requestedName(
            $container->get('filemaker.connection.' . $this->connection)
        );
    }

    public static function __set_state($data)
    {
        return new self($data['connection']);
    }
}
``` 

This is a factory for the repositories for connecting to filemaker - some sort of database.

What would you do instead? Other possibilities I thought of:
* Write 10+ factories that are basically the same (just another configuration key)?
* Write an factory as an abstract class and write 10+ subclasses that have the config key hard-wired?
* Instead of configuration the `$connection` parameter in the constructor use a mapper function to derive this from the `$requestedName`?

**Comment by Ocramius** [comment]
I would simply not throw it at the merged config
