### ISSUE TITLE
Error mapping Entity to table when using extended class

### ISSUE THREAD

**Issue by mctom987** [doctrine/DoctrineORMModule#536]
[issue.tar.gz](https://github.com/doctrine/DoctrineORMModule/files/1444629/issue.tar.gz)
[no-issue.tar.gz](https://github.com/doctrine/DoctrineORMModule/files/1444633/no-issue.tar.gz)

UnconfirmedUser extends User

Field lookups fail on UnconfirmedUser. It looks like there is a mixup with the table spec. The issue can be avoided if UnconfirmedUser instead extends a base AbstractUser with no table spec. That is, with no @Orm\Table(name="table")

I'm not quite sure if this is working as intended, but my thoughts are that if I extend and overwrite the annotations, it should use the new values. I also noticed it does this with the columns, but it seems to be able to match them up better. i.e. email_7 in the extended class, but email_2 in the native.

**Comment by TomHAnderson** [comment]
I think what you need is `inheritance` documented here: http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/inheritance-mapping.html#mapped-superclasses

The short answer is extending a class over a class with metadata won't inherit the metadata.
