### ISSUE TITLE
The name of the DoctrinePaginator Adapter is misleading

### ISSUE THREAD

**Issue by twmobius** [doctrine/DoctrineORMModule#549]
Greetings everyone. First off, great job. 

I think the name DoctrinePaginator (adapter) under `DoctrineORMModule\Paginator\Adapter` is misleading. I often find myself confused looking at the code whether this is an actual extension of `Zend\Paginator\Paginator` or not. 

Shouldn't it be  `DoctrineORMModule\Paginator\Adapter\Doctrine`? Is it just me?

**Comment by Ocramius** [comment]
Possibly, but that train already left the station long ago, and introducing a BC break for a naming improvement would be useless in this particular stance.

Closing as `won't fix`
