### ISSUE TITLE
DBALConnectionFactory requires DB connection when type mappings are used (doctrine_type_mappings)

### ISSUE THREAD

**Issue by fabiang** [doctrine/DoctrineORMModule#551]
Hello,

I'm using type mappings (`doctrine_type_mappings`) for a MySQL database for `enum` to `string` and `bit` to `boolean`, which works like expected.

`DBALConnectionFactory` is calling `getDatabasePlatform()` to get the correct database platform instance, which requires a db connection to be created. I don't always have a DB server running, for example inside a `docker build`.

I don't see an easy fix for this right now, but somehow the factory should try to get the types at a later state when they are required.

My current workaround is to install MySQL inside the container. I'll leave this here for others that have the same problem (assume the base container is Ubuntu/Debian):

```Dockerfile
RUN DEBIAN_FRONTEND=noninteractive apt-get update \
    && echo 'mysql-server mysql-server/root_password password thepassword' | debconf-set-selections \
    && echo 'mysql-server mysql-server/root_password_again password thepassword' | debconf-set-selections \
    && apt-get -y install mysql-server \
    && /etc/init.d/mysql start \
    && DB_HOST=127.0.0.1 DB_PORT=3306 DB_USER=root DB_PASSWORD=thepassword DB_DBNAME= ./vendor/bin/doctrine-module <somecommand> \
    && /etc/init.d/mysql stop \
    && apt-get remove -y mysql-server \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /var/lib/mysql
```

**Comment by Ocramius** [comment]
This is easily fixed by passing in the DB version as part of the config
parameters. If that happens, then no auto-detection will happen, and
therefore no eager connection either.

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by fabiang** [comment]
Perfect, thank you :+1:
