### ISSUE TITLE
Call to a member function getName() on null in Zend Developer Tools

### ISSUE THREAD

**Issue by FrankHouweling** [doctrine/DoctrineORMModule#552]
A similar issue was made earlier in #464 

I have had the same issue today, due to a faulty classname in a relation (Camelcase instead of CamelCase). One of the comments on #464 called for a null check. This is an option, but I would much prefer a clear Exception telling me what to look for. Is it OK if I submit a pull request?

**Comment by TomHAnderson** [comment]
You are always welcome to submit a PR.  We may not accept it, of course, but if you see a fix a PR is appreciated

**Comment by TomHAnderson** [comment]
You are always welcome to submit a PR.  We may not accept it, of course, but if you see a fix a PR is appreciated

**Comment by TomHAnderson** [comment]
Addressed with an exception if the relationship is not found.

**Comment by TomHAnderson** [comment]
#566
