### ISSUE TITLE
Next Release Discussion - PHP 7.1 is go

### ISSUE THREAD

**Issue by TomHAnderson** [doctrine/DoctrineORMModule#557]
Today's release of this library gives us specific PHP 7.1 support only.  No more legacy 5.anything to worry about.  

So for the next release I'd like to 7.1 the hell out of this module.  Let's get all those new bells and whistles 7.1 gives us into this module and lay the groundwork for the future.  

If you've got ideas or questions about this next release please post them here and we'll build a strategy.

**Comment by Ocramius** [comment]
Tagging `2.1.0` will be sufficient

**Comment by TomHAnderson** [comment]
https://github.com/doctrine/DoctrineORMModule/releases/tag/2.1.0
