### ISSUE TITLE
CLI with zendframework/service-manager 2.7 broken

### ISSUE THREAD

**Issue by DennisDobslaf** [doctrine/DoctrineORMModule#558]
https://github.com/doctrine/DoctrineORMModule/blob/c8a865aff5c68c439a834a6f8b88f03433ab5657/src/DoctrineORMModule/Listener/PostCliLoadListener.php#L29

We have a project with zendframework/service-manager version 2.7.10 running. It seems, that the above Listener doesn't get called with the old service-manager. 
I think that's a BC Break in a patch version (1.1.5 -> 1.1.6) of this module that sould be avoided.

**Comment by iwyg** [comment]
@DennisDobslaf using zendframework/zend-servicemanager 3.3.2 and CLI in doctrine-orm-module 1.1.6 is broken, too.

**Comment by Ocramius** [comment]
@DennisDobslaf can anyone pin-point the BC break or write a test reproducing it?

**Comment by fritz-gerneth** [comment]
Seeing the same issue, assuming this to be the breaking change: https://github.com/doctrine/DoctrineORMModule/commit/863a1c993d9d292a2a10b9bfe7b71b4c96179a42#diff-91b9c94f2f305f9007116b4acd7be06bR60 .
The CliFactory gets called during route creation, before modules are bootstrapped.

**Comment by DennisDobslaf** [comment]
@fritz-gerneth I totally agree. That's the point

**Comment by TomHAnderson** [comment]
hotfix is up.  Can I get some testers?  

https://github.com/doctrine/DoctrineORMModule/pull/560

**Comment by DennisDobslaf** [comment]
Installed your fork. Works!

**Comment by TomHAnderson** [comment]
I've pushed out 1.1.7 without a unit test for the CLI tools.  If someone is willing to write those tests I'd appreciate it.
