### ISSUE TITLE
ZendDeveloperTool doctrine toolbar doesn't work anymore

### ISSUE THREAD

**Issue by thomasvargiu** [doctrine/DoctrineORMModule#563]
The zend developer tool doctrine toolbar doesn't work anymore from release 1.1.6.

The problem should be [here](https://github.com/doctrine/DoctrineORMModule/compare/1.1.5...1.1.6#diff-91b9c94f2f305f9007116b4acd7be06bL55)

Now the EventManager is different and it's not the ModuleManager's event manager.

**Comment by TomHAnderson** [comment]
![screen shot 2018-04-14 at 7 25 22 pm](https://user-images.githubusercontent.com/493920/38774005-a728b992-4019-11e8-8d20-c350625ae4bc.png)

I need more information to duplicate the problem.  Here it worked fine for me.

**Comment by TomHAnderson** [comment]
Not in the screenshot: 
```
"require-dev": {
        "zendframework/zend-developer-tools": "^1.1.0",
        "zendframework/zend-test": "^3.0.1"
    }
```

**Comment by thomasvargiu** [comment]
I'm sorry. The ZendDeveloperTool triggers an event `profiler_init`, and this module uses it to register the `sql_logger_collector`. The toolbar is showed but doesn't collect sql queries anymore because the logger is not injected on bootstrap.

The problem is [here](https://github.com/doctrine/DoctrineORMModule/compare/1.1.5...1.1.6#diff-91b9c94f2f305f9007116b4acd7be06bL55) in the release `1.1.6`.

Before v`1.1.6` the listener to initialize the sql logger collector was correctly attached to the `Zend\ModuleManager\ModuleManager`'s event manager, but now you are attaching it to the `Zend\Mvc\Application`'s event manager, the wrong event manager to attach a listener to the `profiler_init` event.

**Comment by TomHAnderson** [comment]
Please try release 1.1.8 and let me know if that fixes the issue.

**Comment by TomHAnderson** [comment]
Also fixed in https://github.com/doctrine/DoctrineORMModule/releases/tag/2.1.2

**Comment by thomasvargiu** [comment]
@TomHAnderson It works with v1.1.8! Thank you!
