### ISSUE TITLE
Fatal Error in Module class at Version 1.1.8

### ISSUE THREAD

**Issue by DennisDobslaf** [doctrine/DoctrineORMModule#567]
https://github.com/doctrine/DoctrineORMModule/blob/a205cc69e35633ced3723629dc54f7edea677841/src/DoctrineORMModule/Module.php#L56

In my case this leads to a fatal error. 
Message:
"Fatal error: Uncaught Error: Call to undefined method Zend\ModuleManager\ModuleManager::getParam() in \vendor\doctrine\doctrine-orm-module\src\DoctrineORMModule\Module.php on line 56"

It seems, that $event->getTarget() is instanceof Zend\ModuleManager\ModuleManager, which has no getParam() method!

**Comment by TomHAnderson** [comment]
Since releaseing 1.1.8 I've had a report that this line **does** work and your report that this line **does not** work.

Here's the line in question: https://github.com/doctrine/DoctrineORMModule/blob/release/1.1.8/src/DoctrineORMModule/Module.php#L56

This is triggered here:
https://github.com/zendframework/ZendDeveloperTools/blob/master/src/Module.php#L63

In the triggering the $event is passed a Zend\ModuleManager\ModuleEvent for 1.1.8 and 2.1.5 which both address this listener.

Please post your `composer show` result.

**Comment by thomasvargiu** [comment]
I think could be a issue between different `zend-modulemanager` releases.

Btw we know that it worked in version `1.1.5`. [Here the difference](https://github.com/doctrine/DoctrineORMModule/compare/1.1.5...1.1.8#diff-91b9c94f2f305f9007116b4acd7be06bL55).

Now the event used for retrieving the ServiceManager is not the same as in release `1.1.5`.
We should change it like this:

```php
$manager
    ->getEventManager()
    ->attach(
        ProfilerEvent::EVENT_PROFILER_INIT,
        function () use ($manager) {
            $container = $manager->getEvent()->getTarget()->getParam('ServiceManager');
            $container->get('doctrine.sql_logger_collector.orm_default');
        }
    );
```

@DennisDobslaf we still need your `composer show` result to understand which module causes the issue.
@TomHAnderson (almost) every package used in `use` statement I think should be in the `composer.json` as requirement, including `zend-eventmanager`, `zend-modulemanager`, etc...

**Comment by DennisDobslaf** [comment]
off course. here is the composer show result

`acelaya/zf2-acmailer                        v4.5.1                                      Mail sending module for Zend Framework 2
bshaffer/oauth2-server-php                  v1.10.0                                     OAuth2 Server for PHP
ccampbell/chromephp                         4.1.0                                       Log variables to the Chrome console (via Chrome Logger Google Chrome extension).
container-interop/container-interop         1.2.0                                       Promoting the interoperability of container objects (DIC, SL, etc.)
dino/dompdf-module                          dev-master 1b6b5b9                          A Zend Framework 2 module for incorporating DOMPDF support.
doctrine/annotations                        v1.6.0                                      Docblock Annotations Parser
doctrine/cache                              v1.7.1                                      Caching library offering an object-oriented API for many cache backends
doctrine/collections                        v1.5.0                                      Collections Abstraction library
doctrine/common                             v2.8.1                                      Common Library for Doctrine projects
doctrine/dbal                               v2.7.1                                      Database Abstraction Layer
doctrine/doctrine-module                    1.2.0                                       Zend Framework Module that provides Doctrine basic functionality required for ORM and ODM modules
doctrine/doctrine-orm-module                1.1.7                                       Zend Framework Module that provides Doctrine ORM functionality
doctrine/inflector                          v1.3.0                                      Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator                       1.1.0                                       A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                              v1.0.1                                      Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
doctrine/orm                                v2.6.1                                      Object-Relational-Mapper for PHP
dompdf/dompdf                               v0.8.2                                      DOMPDF is a CSS 2.1 compliant HTML to PDF converter
dudapiotr/zftable                           dev-master 8c7750c                          Flexible tool to generate table
kriswallsmith/assetic                       v1.4.0                                      Asset Management for PHP
kriswallsmith/buzz                          v0.15.2                                     Lightweight HTTP client
moontoast/math                              1.1.2                                       A mathematics library, providing functionality for large numbers
myclabs/deep-copy                           1.7.0                                       Create deep copies (clones) of your objects
neilime/zf2-twb-bundle                      2.6.1                                       Zend Framework 2 module for easy integration of Twitter Bootstrap
paragonie/random_compat                     v2.0.12                                     PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
phenx/php-font-lib                          0.5.1                                       A library to read, parse, export and make subsets of different types of font files.
phenx/php-svg-lib                           v0.3                                        A library to read, parse and export to PDF SVG files.
phpdocumentor/reflection-common             1.0.1                                       Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock           4.3.0                                       With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is emb...
phpdocumentor/type-resolver                 0.4.0                                      
phpoffice/phpexcel                          1.8.1                                       PHPExcel - OpenXML - Read, Create and Write Spreadsheet documents in PHP - Spreadsheet engine
phpoffice/phpspreadsheet                    1.2.1                                       PHPSpreadsheet - Read, Create and Write Spreadsheet documents in PHP - Spreadsheet engine
phpseclib/phpseclib                         2.0.11                                      PHP Secure Communications Library - Pure-PHP implementations of RSA, AES, SSH2, SFTP, X.509 etc.
phpspec/prophecy                            1.7.5                                       Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage                   4.0.8                                       Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator                   1.4.5                                       FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template                   1.2.1                                       Simple template engine.
phpunit/php-timer                           1.0.9                                       Utility class for timing
phpunit/php-token-stream                    2.0.2                                       Wrapper around PHP's tokenizer extension.
phpunit/phpunit                             5.7.27                                      The PHP Unit Testing framework.
phpunit/phpunit-mock-objects                3.4.4                                       Mock Object library for PHPUnit
psr/container                               1.0.0                                       Common Container Interface (PHP FIG PSR-11)
psr/http-message                            1.0.1                                       Common interface for HTTP messages
psr/log                                     1.0.2                                       Common interface for logging libraries
psr/simple-cache                            1.0.1                                       Common interfaces for simple caching
ramsey/uuid                                 3.7.3                                       Formerly rhumsaa/uuid. A PHP 5.4+ library for generating RFC 4122 version 1, 3, 4, and 5 universally unique identifiers (UUID).
ramsey/uuid-console                         1.1.2                                       A console application for generating UUIDs with ramsey/uuid.
ramsey/uuid-doctrine                        1.4.3                                       Allow the use of a ramsey/uuid UUID as Doctrine field type.
rwoverdijk/assetmanager                     1.7.3                                       An assetmanager module for Zend Framework 2.
sabberworm/php-css-parser                   8.1.0                                       Parser for CSS Files written in PHP
sebastian/code-unit-reverse-lookup          1.0.1                                       Looks up which function or method a line of code belongs to
sebastian/comparator                        1.2.4                                       Provides the functionality to compare PHP values for equality
sebastian/diff                              1.4.3                                       Diff implementation
sebastian/environment                       2.0.0                                       Provides functionality to handle HHVM/PHP environments
sebastian/exporter                          2.0.0                                       Provides the functionality to export PHP variables for visualization
sebastian/global-state                      1.1.1                                       Snapshotting of global state
sebastian/object-enumerator                 2.0.1                                       Traverses array structures and object graphs to enumerate all referenced objects
sebastian/recursion-context                 2.0.0                                       Provides functionality to recursively process PHP variables
sebastian/resource-operations               1.0.0                                       Provides a list of PHP built-in functions that operate on resources
sebastian/version                           1.0.6                                       Library that helps with managing the version number of Git-hosted PHP projects
slm/queue                                   1.0.2                                       Zend Framework module that integrates with various queue management systems
slm/queue-doctrine                          2.0.3                                       Zend Framework 2 module that integrates Doctrine as queuing system
symfony/console                             v3.4.8                                      Symfony Console Component
symfony/debug                               v4.0.8                                      Symfony Debug Component
symfony/polyfill-mbstring                   v1.7.0                                      Symfony polyfill for the Mbstring extension
symfony/process                             v3.4.8                                      Symfony Process Component
symfony/yaml                                v4.0.8                                      Symfony Yaml Component
tecnickcom/tcpdf                            6.2.17                                      TCPDF is a PHP class for generating PDF documents and barcodes.
webmozart/assert                            1.3.0                                       Assertions to validate method input/output with nice error messages.
widmogrod/php-exceptions                    0.1.0                                       Collection PHP exceptions grouped by functionality with nice ::assert API
widmogrod/php-functional                    1.4.0                                       Functors, Applicative and Monads are fascinating concept. Purpose of this library is to explore them in OOP PHP world.
widmogrod/zf2-assetic-module                1.6.0                                       Zend Framework 2 module that provides complete integration of Assetic library
wsdltophp/packagebase                       1.0.11                                      Contains the base classes to be used by classes generated by wsdltophp/packagegenerator
zendframework/zend-authentication           2.6.0                                       provides an API for authentication and includes concrete authentication adapters for common use case scenarios
zendframework/zend-barcode                  2.7.0                                       provides a generic way to generate barcodes
zendframework/zend-cache                    2.7.2                                       provides a generic way to cache any data
zendframework/zend-captcha                  2.7.1                                      
zendframework/zend-code                     2.6.3                                       provides facilities to generate arbitrary code using an object oriented interface
zendframework/zend-config                   2.6.0                                       provides a nested object property based user interface for accessing this configuration data within application code
zendframework/zend-console                  2.7.0                                       Build console applications using getopt syntax or routing, complete with prompts
zendframework/zend-crypt                    2.6.0                                      
zendframework/zend-db                       2.9.3                                       Database abstraction layer, SQL abstraction, result set abstraction, and RowDataGateway and TableDataGateway implementations
zendframework/zend-debug                    2.5.1                                      
zendframework/zend-developer-tools          1.1.1                                       Module for developer and debug tools for use with zend-mvc applications.
zendframework/zend-di                       2.6.1                                      
zendframework/zend-diactoros                1.7.1                                       PSR HTTP Message implementations
zendframework/zend-dom                      2.7.1                                       provides tools for working with DOM documents and structures
zendframework/zend-escaper                  2.5.2                                      
zendframework/zend-eventmanager             2.6.4                                      
zendframework/zend-feed                     2.9.0                                       provides functionality for consuming RSS and Atom feeds
zendframework/zend-file                     2.7.1                                      
zendframework/zend-filter                   2.8.0                                       provides a set of commonly needed data filters
zendframework/zend-form                     2.11.0                                      Validate and display simple and complex forms, casting forms to business objects and vice versa
zendframework/zend-http                     2.7.0                                       provides an easy interface for performing Hyper-Text Transfer Protocol (HTTP) requests
zendframework/zend-hydrator                 1.1.0                                      
zendframework/zend-i18n                     2.7.4                                      
zendframework/zend-i18n-resources           2.5.2                                       Provides validator translations for zend-i18n's Translator
zendframework/zend-inputfilter              2.8.1                                       Normalize and validate input sets from the web, APIs, the CLI, and more, including files
zendframework/zend-json                     2.6.1                                       provides convenience methods for serializing native PHP to JSON and decoding JSON to native PHP
zendframework/zend-loader                   2.5.1                                      
zendframework/zend-log                      2.10.0                                      component for general purpose logging
zendframework/zend-mail                     2.9.0                                       provides generalized functionality to compose and send both text and MIME-compliant multipart e-mail messages
zendframework/zend-math                     2.7.0                                      
zendframework/zend-memory                   2.5.2                                      
zendframework/zend-mime                     2.7.0                                       Create and parse MIME messages and parts
zendframework/zend-modulemanager            2.8.2                                       Modular application system for zend-mvc applications
zendframework/zend-mvc                      2.7.13                                     
zendframework/zend-navigation               2.8.2                                       provides support for managing trees of pointers to web pages
zendframework/zend-paginator                2.8.1                                       zend-paginator is a flexible component for paginating collections of data and presenting that data to users.
zendframework/zend-permissions-acl          2.6.0                                       provides a lightweight and flexible access control list (ACL) implementation for privileges management
zendframework/zend-permissions-rbac         2.6.0                                       provides a role-based access control management
zendframework/zend-progressbar              2.5.2                                       component to create and update progressbars in different environments
zendframework/zend-psr7bridge               0.2.2                                       PSR-7 <-> Zend\Http bridge
zendframework/zend-serializer               2.8.1                                       provides an adapter based interface to simply generate storable representation of PHP types by different facilities, and recover
zendframework/zend-server                   2.7.0                                      
zendframework/zend-servicemanager           2.7.10                                     
zendframework/zend-session                  2.8.5                                       manage and preserve session data, a logical complement of cookie data, across multiple page requests by the same client
zendframework/zend-soap                     2.7.0                                      
zendframework/zend-stdlib                   2.7.7                                      
zendframework/zend-tag                      2.6.1                                       a component suite which provides a facility to work with taggable Items
zendframework/zend-test                     2.6.1                                      
zendframework/zend-text                     2.6.0                                      
zendframework/zend-uri                      2.6.0                                       a component that aids in manipulating and validating » Uniform Resource Identifiers (URIs)
zendframework/zend-validator                2.10.2                                      provides a set of commonly needed validators
zendframework/zend-version                  2.5.1                                      
zendframework/zend-view                     2.10.0                                      provides a system of helpers, output filters, and variable escaping
zendframework/zend-xmlrpc                   2.6.2                                      
zendframework/zendframework                 2.5.3                                       Zend Framework 2
zendframework/zendpdf                       dev-master b3d00f8                          Zend Pdf Component
zendframework/zendxml                       1.0.2                                       Utility library for XML usage, best practices, and security in PHP
zf-commons/zfc-rbac                         v2.6.3                                      Zend Framework 2 Module that provides a layer of features of Zend\Permissions\Rbac
zfcampus/zf-api-problem                     1.2.3                                       ZF2 Module providing API-Problem assets and rendering
zfcampus/zf-apigility                       1.3.0                                       Apigility module for Zend Framework
zfcampus/zf-apigility-admin                 1.5.13                                      Apigility Admin module
zfcampus/zf-apigility-admin-ui              1.3.9                                       Apigility Admin UI module
zfcampus/zf-apigility-provider              1.2.0                                       Apigility interfaces
zfcampus/zf-configuration                   1.3.2                                       Zend Framework module providing a REST resource for manipulating configuration
zfcampus/zf-content-negotiation             1.3.3                                       ZF2 Module providing content-negotiation features
zfcampus/zf-content-validation              1.3.6                                       Zend Framework module providing incoming content validation
zfcampus/zf-development-mode                2.1.2                                       ZF2 development mode module
zfcampus/zf-hal                             1.4.2                                       ZF2 Module providing Hypermedia Application Language assets and rendering
zfcampus/zf-mvc-auth                        1.4.3                                       ZF2 Module providing Authentication and Authorization events and infrastructure
zfcampus/zf-oauth2                          1.4.0                                       ZF2 module for implementing an OAuth2 server
zfcampus/zf-rest                            1.3.3                                       ZF Module providing structure for RESTful resources
zfcampus/zf-rpc                             1.3.1                                       ZF2 Module for simplifying the creation of RPC services
zfcampus/zf-versioning                      1.2.1                                       ZF2 Module providing listeners and route prototypes for implementing API versioning
zfr/rbac                                    1.2.0                                       Zend Framework 3 prototype for Zend\Permissions\Rbac.
`

**Comment by thomasvargiu** [comment]
The problem is a BC break with `zend-eventmanager` `2.7.x` and 3.x`.

Using the `trigger()` method, in version [`3.x`](https://github.com/zendframework/zend-eventmanager/blob/release-3.2.0/src/EventManager.php#L137) a new event is created, and the target is the event.
In version [`2.7`](https://github.com/zendframework/zend-eventmanager/blob/release-2.6.4/src/EventManager.php) the event is the original event, where the target is the `Zend\ModuleManager\ModuleManager`.

I think is a bug in ZendDeveloperTools that it's not really compatible with both versions.

Like I suggested above, those changes should fix the problem.
