### ISSUE TITLE
orm:ensure-production-settings should complain about all issues at once

### ISSUE THREAD

**Issue by bitwombat** [doctrine/DoctrineORMModule#569]
Minor issue.

I noticed that when I run:

    doctrine-module orm:ensure-production-settings

It complains:

    [ERROR] Query Cache uses a non-persistent cache driver

And when I fix that, it complains:

    [ERROR] Metadata Cache uses a non-persistent cache driver

When I fix all caches, it then says:

   [ERROR] Proxy Classes are always regenerating.

It would be helpful if it would tell me all of the complaints at once (warnings instead of errors?)

**Comment by TomHAnderson** [comment]
This belongs in `doctrine/doctrine-module`

**Comment by bitwombat** [comment]
Done
https://github.com/doctrine/DoctrineModule/issues/637
