### ISSUE TITLE
Cache config in module.config.php or local.php?

### ISSUE THREAD

**Issue by bitwombat** [doctrine/DoctrineORMModule#570]
At https://github.com/doctrine/DoctrineORMModule/blob/master/docs/cache.md

It says

> If you want to set a cache for query, result and metadata, you can specify this inside your module.config.php

Wouldn't this more likely be in `local.php` as they are settings for production?

Or maybe the persistent (production)  caches defined in `global.php` but overridden in `development.local.php`?

`module.config.php` seems to be the least likely place.

Please clarify if I'm missing something behind the recommendation.

**Comment by TomHAnderson** [comment]
You're right.  Recommending `module.config.php` is not correct.  Would you like to correct the docs in a PR else I'll do it if you don't want the commit credit.

**Comment by bitwombat** [comment]
Will absolutely do the PR.
But, as described, I'm unsure where the best place for those settings would be.  Does it come down to opinion?

**Comment by TomHAnderson** [comment]
Local.php

**Comment by TomHAnderson** [comment]
Meged PR #571
