### ISSUE TITLE
handleRequiredAssociation default value

### ISSUE THREAD

**Issue by porebskk** [doctrine/DoctrineORMModule#572]
Hello,

it seems that for input-specs the method ElementAnnotationsListener::handleRequiredAssociation defaults to required=true. The JoinColumn annotation in contrast defaults to nullable=true which should translate to required=false. The problem here is that the default values of the annotation is not transfered to the association-mapping from doctrines classmetadata.  
I would expect the opposite, that required defaults to false. If my assumption are correct, I would gladly provide a pull request.

Greetings

**Comment by TomHAnderson** [comment]
I believe I see what you're saying.  That the metadata is correct and the handling of that metadata is incorrect in this module.  If you can correct it I'll merge it in.  IMHO form handing in this module is not as widely used today.

**Comment by TomHAnderson** [comment]
Closing due to age.
