### ISSUE TITLE
invalidTargetEntityClass

### ISSUE THREAD

**Issue by ma9ni** [doctrine/DoctrineORMModule#573]
20:03:26 ERROR     [console] Error thrown while running command "doctrine:schema:update -f -v". Message: "The target-entity ScolariteBundle\Entity\Facture cannot be found in 'ScolariteBundle\Entity\Inscription#idDoc'." ["exception" => Doctrine\ORM\Mapping\MappingException { …},"command" => "doctrine:schema:update -f -v","message" => "The target-entity ScolariteBundle\Entity\Facture cannot be found in 'ScolariteBundle\Entity\Inscription#idDoc'."] []

In MappingException.php line 772:
                                                                                                                   
  [Doctrine\ORM\Mapping\MappingException]                                                                          
  The target-entity ScolariteBundle\Entity\Facture cannot be found in 'ScolariteBundle\Entity\Inscription#idDoc'.  
                                                                                                                   

Exception trace:
 Doctrine\ORM\Mapping\MappingException::invalidTargetEntityClass() at C:\wamp64\www\EPAdmin\vendor\doctrine\orm\lib\Doctrine\ORM\Mapping\ClassMetadataInfo.php:1029
 Doctrine\ORM\Mapping\ClassMetadataInfo->validateAssociations() at C:\wamp64\www\EPAdmin\vendor\doctrine\orm\lib\Doctrine\ORM\Mapping\ClassMetadataFactory.php:266
 Doctrine\ORM\Mapping\ClassMetadataFactory->validateRuntimeMetadata() at C:\wamp64\www\EPAdmin\vendor\doctrine\orm\lib\Doctrine\ORM\Mapping\ClassMetadataFactory.php:245
 Doctrine\ORM\Mapping\ClassMetadataFactory->doLoadMetadata() at C:\wamp64\www\EPAdmin\vendor\doctrine\persistence\lib\Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory.php:305
 Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata() at C:\wamp64\www\EPAdmin\vendor\doctrine\orm\lib\Doctrine\ORM\Mapping\ClassMetadataFactory.php:78
 Doctrine\ORM\Mapping\ClassMetadataFactory->loadMetadata() at C:\wamp64\www\EPAdmin\vendor\doctrine\persistence\lib\Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory.php:183
 Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor() at C:\wamp64\www\EPAdmin\vendor\doctrine\persistence\lib\Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory.php:89
 Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getAllMetadata() at C:\wamp64\www\EPAdmin\vendor\doctrine\orm\lib\Doctrine\ORM\Tools\Console\Command\SchemaTool\AbstractCommand.php:62
 Doctrine\ORM\Tools\Console\Command\SchemaTool\AbstractCommand->execute() at C:\wamp64\www\EPAdmin\vendor\doctrine\doctrine-bundle\Command\Proxy\UpdateSchemaDoctrineCommand.php:35
 Doctrine\Bundle\DoctrineBundle\Command\Proxy\UpdateSchemaDoctrineCommand->execute() at C:\wamp64\www\EPAdmin\vendor\symfony\symfony\src\Symfony\Component\Console\Command\Command.php:251
 Symfony\Component\Console\Command\Command->run() at C:\wamp64\www\EPAdmin\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:964
 Symfony\Component\Console\Application->doRunCommand() at C:\wamp64\www\EPAdmin\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php:86
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at C:\wamp64\www\EPAdmin\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:248
 Symfony\Component\Console\Application->doRun() at C:\wamp64\www\EPAdmin\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php:74
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at C:\wamp64\www\EPAdmin\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:148
 Symfony\Component\Console\Application->run() at C:\wamp64\www\EPAdmin\bin\console:29

**Comment by Ocramius** [comment]
This is invalid: you need to correctly re-configure your autoloader and check for typos.
