### ISSUE TITLE
Connect To Oracle By Symfony 4

### ISSUE THREAD

**Issue by falahatiali** [doctrine/DoctrineORMModule#575]
Hello Everyone
I wanna Connect to Oracle Database into Symfony 4 Framework.
How can I this action by Doctrine ? 
is it Impossible that we Create Table And Database through migration ?

**Comment by Ocramius** [comment]
Closing here, since this is not a bug. Connection parameters for OCI8 can be found in the `doctrine/dbal` documentation.
