### ISSUE TITLE
Is there any BC breaks between 1.* and 2.* versions?

### ISSUE THREAD

**Issue by svycka** [doctrine/DoctrineORMModule#577]
I see that https://github.com/doctrine/DoctrineORMModule/blob/master/UPGRADE.md no longer updated so I am asking here but maybe UPGRADE.md should be updated.

**Comment by TomHAnderson** [comment]
The issues fixed and commits made are all available on this repository.  Contributing your idea of bringing the UPGRADE.md file up to date would be welcome.

As for your question, the primary difference between 1.x & 2.x is the use of zend-hydrator instead of the hydrators in zend-stdlib.
