### ISSUE TITLE
Object Manager does not get injected into Hydrator when using form annotations

### ISSUE THREAD

**Issue by cbichis** [doctrine/DoctrineORMModule#580]
Hi,

If using annotations, for Hydrator the Object Manager doesnt get injected it seems...

```php
/**
 * @ORM\Entity
 * @ORM\Table(name="mytable")
 * @Annotation\Type("Form")
 * @Annotation\Name("mytable")
 * @Annotation\Hydrator("\DoctrineModule\Stdlib\Hydrator\DoctrineObject")
 */
```

The error is:

    Too few arguments to function DoctrineModule\Stdlib\Hydrator\DoctrineObject::__construct(), 0 passed in myproject/vendor/zendframework/zend-form/src/FormElementManager/FormElementManagerTrait.php on line 84 and at least 1 expected

The annotations are quite fine to use for some basic forms / simpler entities and operations.

**Comment by TomHAnderson** [comment]
I suggest you create your own hydrator which extends from DoctrineObject and uses a factory to inject the Object Manager.
