### ISSUE TITLE
Zend Hydrator update

### ISSUE THREAD

**Issue by alexz707** [doctrine/DoctrineORMModule#587]
HI!
The OrmModule requires Zend-Hydrator version ^2.3.
Are there any plans on updating this depency to the latest version ? 3.0.* 

Thanks
Alex

**Comment by webimpress** [comment]
@alexz707 Yes, see: https://github.com/doctrine/DoctrineModule/pull/644

**Comment by alexz707** [comment]
@webimpress that looks great! hopefully a maintainer will respond to that...
Nice work! thanks!

**Comment by SenseException** [comment]
@alexz707 Does the PR of @webimpress cover your use case? If yes, I'd like to close your issue as a duplicate.

**Comment by webimpress** [comment]
@SenseException I wouldn't close it for now, as my PR is to `DoctrineModule` and it must be done before we can update that library `DoctrineORMModule`.

**Comment by alexz707** [comment]
@SenseException  @webimpress was a bit faster than me but he pointed it out..

**Comment by diego-sorribas** [comment]
Hi there! Any update on this? Thanks!

**Comment by michalbundyra** [comment]
@diego-sorribas See #602 

DoctrineModule is already updated and works with laminas-hydrator v3.

**Comment by diego-sorribas** [comment]
But this package is still pointing to doctrine-module: 2.1  or I'm wrong?

**Comment by TomHAnderson** [comment]
It is a process to move to Laminas, @diego-sorribas .  The doctrine-laminas-hydrator v2.0.1 was just released today.  Next must follow DoctrineModule and only then can this module be acted upon.

Questions?

**Comment by TomHAnderson** [comment]
This has been released as https://github.com/doctrine/DoctrineORMModule/releases/tag/3.0.0
