### ISSUE TITLE
Where condition ORM

### ISSUE THREAD

**Issue by mssyogi** [doctrine/DoctrineORMModule#597]
/**
     * @ORM\ManyToMany(targetEntity="Institution")
     * @ORM\JoinTable(name="institutions_users",
     *      joinColumns={@ORM\JoinColumn(name="user_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="institution_id", referencedColumnName="id")}
     *  )
     *
     * @Serializer\Groups({"whoami", "default"})
     */
How i can add where clause in it

**Comment by Ocramius** [comment]
Seems unrelated to the module: closing here.

Please re-open against the right repository **after** clarifying:

 * current behavior
 * expected behavior
 * code to reproduce the problem (if there is a problem)

**Comment by mssyogi** [comment]
I mean how I can add where condition with joins

**Comment by Ocramius** [comment]
That's not supported by design
