### ISSUE TITLE
DoctrineModule\Stdlib\Hydrator\DoctrineObject is not available anymore

### ISSUE THREAD

**Issue by BigMichi1** [doctrine/DoctrineORMModule#610]
today i upgrade to doctrine/doctrine-orm-module 3.0.1 and i have now a lot of broken tests.
the reason for this is that in config.php there is still an import to the old package of the DoctrineObject

use DoctrineModule\Stdlib\Hydrator\DoctrineObject;

in my updated code this class is now in Doctrine\Laminas\Hydrator\DoctrineObject

**Comment by TomHAnderson** [comment]
That is right.  The major version number update for doctrine-orm-module comes with new namespaces.  The DoctrineObject has been moved to https://github.com/doctrine/doctrine-laminas-hydrator which is a dependency of DoctrineModule ^4.0
