### ISSUE TITLE
Missing Class Dependency results in Class Not Found?

### ISSUE THREAD

**Issue by Dwarfex** [doctrine/DoctrineORMModule#625]
I'm having issues installing the latests doctrine packages with laminas.
I was using
"doctrine/doctrine-orm-module": "^3.0",
and it seems as if i got into a situiation where 

The referenced MappingDriverChain Class within the most recent /config/module.config.php 

Doctrine\Common\Persistence\Mapping\Driver\MappingDriverChain
has become
Doctrine\Persistence\Mapping\Driver\MappingDriverChain;

and thus moved from the doctrine/common to the doctrine/persistence package?

see: https://github.com/doctrine/DoctrineORMModule/blob/d9b473d74cda0748338e0783c45e521bbd848320/config/module.config.php#L3

I'm sorry if this is a bit unspecific - but i hadn't had time to troubleshoot in a deeper manner.
This was also referenced here: https://www.php.de/forum/webentwicklung/php-frameworks/1577266-composer-installiert-doctrine-module-f%C3%BCr-laminas-nicht-richtig

**Comment by Sebastian-Habiger** [comment]
As mentioned in the link https://www.php.de/forum/webentwicklung/php-frameworks/1577266-composer-installiert-doctrine-module-f%C3%BCr-laminas-nicht-richti @Dwarfex already posted downgrading doctrine module to version 4.0.2 fixed the problem for me.

Thank you

**Comment by glennschmidt** [comment]
`doctrine/doctrine-orm-module` seems to be incompatible with `doctrine/orm 2.8.*`
My solution was to pin `"doctrine/orm": "2.7.*"`

**Comment by TomHAnderson** [comment]
Fixed with https://github.com/doctrine/DoctrineORMModule/pull/633

**Comment by TomHAnderson** [comment]
https://github.com/doctrine/DoctrineORMModule/releases/tag/3.0.6
