### ISSUE TITLE
Connect migrations with entities

### ISSUE THREAD

**Issue by SylvanoTombo** [doctrine/DoctrineORMModule#626]
How can i generate migration from my entities ?

**Comment by TomHAnderson** [comment]
Use the schema tool to create your sql then manually create your migration.  That is my process.

**Comment by SylvanoTombo** [comment]
@TomHAnderson , thanks.

But is this can be done automatically, like a command make:migration in symfony?

**Comment by TomHAnderson** [comment]
That command does not exist in Laminas integrations.  If you wanted to build such a thing the first step is to familiarize yourself with the latest migrations tool.  That tool is not supported by DoctrineORMModule but perhaps you could catalyze its adoption.

**Comment by Nakira** [comment]
DoctrineORMModule was supporting migrations with Zend framework 3  
  
I don't really get how that was not kept, as this is a crucial tool.  
  
@TomHAnderson do we know what's missing to use it at latest version with laminas  
Could you explain a bit more about this commit ce63507 ?

**Comment by MadCat34** [comment]
Hi,

Doctrine Migrations 2.X is working with DoctrineORMModule

`composer require doctrine/migrations:^2.0`


Then, add config in autoload/

```
return [
    'doctrine' => [
        'migrations_configuration' => [
            'orm_default' => [
                'directory' => 'data/migrations',
                'name' => 'Migrations Name',
                'namespace' => 'Migrations',
                'table' => 'migrations_table',
                'column' => 'version',
            ],
        ],
    ]
];
```

Using ./vendor/bin/doctrine-module you now have access to migrations commands

**Comment by TomHAnderson** [comment]
@Nakira the change to the commit you asked about was because the command line `php public/index.php migrations/*` are not ported to 2.0 yet.
