### ISSUE TITLE
Cannot install/update if using doctrine/migrations > v3

### ISSUE THREAD

**Issue by waltertamboer** [doctrine/DoctrineORMModule#634]
The module has this dev requirement:

```
doctrine/migrations: ^1.5 || ^2.0, < 2.3.0
```

Therefor it becomes impossible to upgrade the module if you use doctrine/migrations >=3.0

**Comment by TomHAnderson** [comment]
OK, yes, I know.   Unless you use the .phar file of course.  

Did you have something you wanted to ask or are you "just sayin'"?

**Comment by TomHAnderson** [comment]
And, I'm very open to supporting migrations >= 3.0.  But we need someone to write the integration.  Just sayin'.

**Comment by waltertamboer** [comment]
Not sure what you mean but I would consider this an issue and that's why I reported it.

**Comment by TomHAnderson** [comment]
Works as designed.  Would love someone with a vested interest in migrations 3.0 to step up and catalyze development.

**Comment by TomHAnderson** [comment]
@waltertamboer I've started work on Migrations 3 support for this module: https://github.com/doctrine/DoctrineORMModule/pull/636

**Comment by waltertamboer** [comment]
That's great! Let me know if you need help testing your changes.

**Comment by TomHAnderson** [comment]
@waltertamboer it's time to take you up on your offer to test.  The PR https://github.com/doctrine/DoctrineORMModule/pull/636 works for me and passes all unit tests.  Please checkout the 3.1.0 branch and merge the PR into it in order to test.

**Comment by TomHAnderson** [comment]
https://github.com/doctrine/DoctrineORMModule/releases/tag/3.1.0
