### ISSUE TITLE
MigrationsConfigurationHelper can not find ConfigurationHelperInterface

### ISSUE THREAD

**Issue by kokspflanze** [doctrine/DoctrineORMModule#639]
i updated to the latest version 3.0.7 and i dont have the doctrine-migrations.

i have now the following error. 

```
PHP Fatal error:  Interface 'Doctrine\Migrations\Tools\Console\Helper\ConfigurationHelperInterface' not found in /var/www/page/vendor/doctrine/doctrine-orm-module/src/DoctrineORMModule/Console/Helper/MigrationsConfigurationHelper.php on line 17
```

i just switched back to 3.0.6 and its working again.

Im not 100% in the migrations, so i can not create that fix. =(

**Comment by TomHAnderson** [comment]
Thank you for the report.  The error makes sense and I'll have an updated release soon.

**Comment by Blaimi** [comment]
this is the buggy commit: https://github.com/doctrine/DoctrineORMModule/commit/8655dcba0810bc5f0c89cb0be1157de97fb0bc27

**Comment by TomHAnderson** [comment]
This is the PR to fix it:  https://github.com/doctrine/DoctrineORMModule/pull/640

**Comment by TomHAnderson** [comment]
Fixed in https://github.com/doctrine/DoctrineORMModule/releases/tag/3.0.8

**Comment by kokspflanze** [comment]
thanks works=)
