### ISSUE TITLE
`organize_migrations` configuration option should be opt-in.

### ISSUE THREAD

**Issue by bfoosness** [doctrine/DoctrineORMModule#641]
The `organize_migrations` configuration key causes new migrations to be organized by year by default:

https://github.com/doctrine/DoctrineORMModule/blob/1d9170b7f484fb5c59335783458a0d96769806a9/config/module.config.php#L171

But there's no option that can override and undo this setting once it's set:

https://github.com/doctrine/migrations/blob/3.0.1/lib/Doctrine/Migrations/Configuration/Configuration.php#L184

Could the `organize_migrations` key be removed from `module.config.php` so that it's opt-in?

**Comment by TomHAnderson** [comment]
You're right, @bfoosness 

This is a problem in the migrations library IMHO.  Because the initial value is `false` it should be possible to set it back to `false` but it is not.

I'm going to accept your request and release a new version with `organize_migrations` commented out for `orm_default` then submit a PR to the migrations project.

**Comment by bfoosness** [comment]
I do see value in this module being more opinionated and organizing migrations by default, so I agree with you that the better solution is a change to the migrations library. Thank you for your help, @TomHAnderson!

**Comment by TomHAnderson** [comment]
https://github.com/doctrine/DoctrineORMModule/releases/tag/3.1.1

**Comment by TomHAnderson** [comment]
I too think being opinionated would be good however it is more prudent to continue with the defaults of migrations 2 which is to set `organize_migrations` to false.  So version 3.1.1 will continue to be the default for this repo.

**Comment by TomHAnderson** [comment]
https://github.com/doctrine/migrations/pull/1075
