### ISSUE TITLE
PHP 8.0 Support

### ISSUE THREAD

**Issue by FabianKoestring** [doctrine/DoctrineORMModule#649]
Will this Module support PHP 8.0 in near future? Are there any plans of supporting php 8.0?

**Comment by TomHAnderson** [comment]
Of course there are.  Ill keep this issue open and add that shortly.

**Comment by FabianKoestring** [comment]
@TomHAnderson sry when I'm annoying but what exactly do you mean by shortly? 😉🙏

**Comment by TomHAnderson** [comment]
I guess I meant as soon as it's in my interest to enable it.  If you've got a pressing need for it I implore you to create a PR and we'll get it merged.

**Comment by Slamdunk** [comment]
PHP 8 support released in v4
