### ISSUE TITLE
Class 'DoctrineORMModule\Service\MigrationsConfigurationFactory' not found

### ISSUE THREAD

**Issue by snapshotpl** [doctrine/DoctrineORMModule#651]
https://github.com/doctrine/DoctrineORMModule/blob/3.1.x/config/module.config.php#L232

**Comment by snapshotpl** [comment]
https://github.com/doctrine/DoctrineORMModule/pull/652/checks?check_run_id=1695028706#step:6:10

**Comment by TomHAnderson** [comment]
This class is not used and should be removed from the config.

**Comment by snapshotpl** [comment]
Are you sure? Looks like it's probably related with doctine-module

```
 Uncaught Exception Error: "Class 'DoctrineORMModule\Service\MigrationsConfigurationFactory' not found" at /var/www/vendor/doctrine/doctrine-module/src/DoctrineModule/ServiceFactory/AbstractDoctrineServiceFactory.php line 42
```

**Comment by TomHAnderson** [comment]
The `doctrine-module` code is a more generic service manager use.  Can you post the full exception please and steps to duplicate if you have them?

**Comment by snapshotpl** [comment]
That was because I have my custom factories. After revert this changes works fine.
