### ISSUE TITLE
Inject container into a Migration

### ISSUE THREAD

**Issue by bdudelsack** [doctrine/DoctrineORMModule#655]
I know it's maybe not the best pattern, but i would like to inject a `ContainerInterface` to a migration. It should be possible by decorating the `MigrationFactory` in the `DependencyFactory`. It is possible in `DoctrineMigrationsBundle` for Symfony but is not possible in this module for laminas.

I don't see any possibility other than writing my own `MigrationsCommandFactory` at the moment. I could do the PR myself but i need some advice what's the best way to do it.

**Comment by bdudelsack** [comment]
I looked into the PRs and https://github.com/doctrine/DoctrineORMModule/pull/653 would likely sove it

**Comment by TomHAnderson** [comment]
https://github.com/doctrine/DoctrineORMModule/releases/tag/3.2.0
