### ISSUE TITLE
Support for DoctrineORMModule\Form\Annotation\AnnotationBuilder in 4.x series

### ISSUE THREAD

**Issue by cbichis** [doctrine/DoctrineORMModule#666]
After migrating to 4.0 it seems the

DoctrineORMModule\Form\Annotation\AnnotationBuilder

is missing. Is this a bug or not?

I cant find something related to this into documentation.

**Comment by cbichis** [comment]
It seems Laminas Form v3 is supporting everything needed for this:

https://docs.laminas.dev/laminas-form/v3/form-creation/attributes-or-annotations/

**Comment by TomHAnderson** [comment]
The release for 4.0.0 which removed support for annotations is here:  https://github.com/doctrine/DoctrineORMModule/releases/tag/4.0.0
That decision was made due to https://github.com/laminas/laminas-form/pull/75#issuecomment-801963975

If Form v3 does in fact support annotations again it may not be as simple as putting that code back into this module.  However, this project could really use a champion to re-enable annotations.  I would support this effort.  Contributions by interested parties are the best sort.

**Comment by driehle** [comment]
@cbichis I re-added the annotation builder in #694. Could you please check if that solves your needs? You can install it as follows:

```json
{
    "require": {
        "doctrine/doctrine-orm-module": "dev-feature/form-builder as 4.2.0",
        ....
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/driehle/DoctrineORMModule"
        }
    ]
}
```

Please note that it only works with laminas-form 3.0, not with 2.x. Usage is slighly different:

```php
// using PhpDoc annotations
$objectManager = $container->get(ObjectManager::class);
$builder = new \DoctrineORMModule\Form\Annotation\EntityBasedFormBuilder($objectManager);

// alternatively, to use PHP8 attributes
$objectManager = $container->get(ObjectManager::class);
$attributeBuilder = new \Laminas\Form\Annotation\AttributeBuilder();
$builder = new \DoctrineORMModule\Form\Annotation\EntityBasedFormBuilder($objectManager, $attributeBuilder);

// if you need access to the event manager
$builder->getBuilder()->getEventManager();

// if you need access to the form factory
$builder->getBuilder()->getFormFactory();
```

After this, usage should be the same as in DoctrineORMModule 3.x:

```php
// get form specification
$entity = new User();
$formSpec = $builder->getFormSpecification($entity);

// get form
$formSpec = $builder->createForm($entity);
```

**Comment by cbichis** [comment]
Thanks, i'll test.

**Comment by cbichis** [comment]
It seems to be working, based on some short tests I have ran today.

I cant do some extensive testing now as I am need to make compatible some additional parts of the app before (nothing Annotations related).

**Comment by driehle** [comment]
Version 4.2.0 with support for annotations is now released.
