### ISSUE TITLE
Installation with PHP 8

### ISSUE THREAD

**Issue by defaultpage** [doctrine/DoctrineORMModule#667]
Hi! This is just note for an end users.

In regard to https://github.com/doctrine/DoctrineModule/pull/727 and https://github.com/doctrine/DoctrineModule/pull/725, end-users (i.e. not this library) need to specify the following in their `composer.json` for running DoctrineModule (and DoctrineORMModule) with PHP 8.0:

```composer
    "replace": {
        "laminas/laminas-cache-storage-adapter-apc": "*",
        "laminas/laminas-cache-storage-adapter-dba": "*",
        "laminas/laminas-cache-storage-adapter-memcache": "*",
        "laminas/laminas-cache-storage-adapter-memcached": "*",
        "laminas/laminas-cache-storage-adapter-mongodb": "*",
        "laminas/laminas-cache-storage-adapter-wincache": "*",
        "laminas/laminas-cache-storage-adapter-xcache": "*",
        "laminas/laminas-cache-storage-adapter-zend-server": "*"
    }

```

I'll mark this issue as closed when https://github.com/doctrine/DoctrineModule/pull/725 will be closed.

**Comment by driehle** [comment]
I'll close this issue, as this is now explicitly mentioned in the [readme](https://github.com/doctrine/DoctrineORMModule) and in the [docs for 4.1](https://www.doctrine-project.org/projects/doctrine-orm-module/en/4.1/index.html).
