### ISSUE TITLE
Paginators Cache ID is too generic

### ISSUE THREAD

**Issue by FabianKoestring** [doctrine/DoctrineORMModule#669]
Hey there,

it seems like the ` _getCacheInternalId()` Method in `laminas-paginator/src/Paginator.php` does create too generic cache ids. I use `DoctrinePaginator` with multiple `WHERE` parts. The generated cache key is the same as the `DoctrinePaginator` without `WHERE` part.

There is an exception for `DbSelect` instances. See https://github.com/laminas/laminas-paginator/pull/6

Is there a way to get around this problem?

**Comment by FabianKoestring** [comment]
Maybe implement `\JsonSerializable`?

**Comment by TomHAnderson** [comment]
Can you provide a unit test for this?  Though your description and the other bug reference are useful, seeing this in code would be most beneficial.

**Comment by FabianKoestring** [comment]
@TomHAnderson I cant provide a failing unit test because the relevant parts are `protected` or `private`. Maybe following laminas example explains the problem a little bit more.

### Working example (Different pages creates different cache id´s)
```php
        /** @var EntityManager $entityManager */
        $entityManager = $container->get(EntityManager::class);

        /** @var StorageAdapterFactoryInterface $storageFactory */
        $storageFactory = $container->get(StorageAdapterFactoryInterface::class);

        $cache = $storageFactory->create(
            'filesystem',
            [
                'cache_dir' => '/var/www/stack/src/crm/data/cache/'
            ],
            [
                ['name' => 'serializer'],
            ]
        );
        
        $queryBuilder = new QueryBuilder($entityManager);
        $queryBuilder
            ->select('t0')
            ->from(Entity\City', 't0');

        $doctrinePaginator = new DoctrinePaginator($queryBuilder);
        $doctrinePaginatorAdapter = new DoctrinePaginatorAdapter($doctrinePaginator);

        $paginator = new LaminasPaginator($doctrinePaginatorAdapter);
        $paginator::setCache($cache);

        $paginator->getItemsByPage(1); //_getCacheId() => Laminas_Paginator_1_07381ecd2347c3ccacd038f34ab9c699
        $paginator->getItemsByPage(2); //_getCacheId() => Laminas_Paginator_2_07381ecd2347c3ccacd038f34ab9c699
```

### Failing example (Different where parts creates same cache id`s)
```php
        /** @var EntityManager $entityManager */
        $entityManager = $container->get(EntityManager::class);

        /** @var StorageAdapterFactoryInterface $storageFactory */
        $storageFactory = $container->get(StorageAdapterFactoryInterface::class);

        $cache = $storageFactory->create(
            'filesystem',
            [
                'cache_dir' => '/var/www/stack/src/crm/data/cache/'
            ],
            [
                ['name' => 'serializer'],
            ]
        );

        $queryBuilder1 = new QueryBuilder($entityManager);
        $queryBuilder1
            ->select('t0')
            ->from('Entity\City', 't0')
            ->where(
                $queryBuilder1->expr()->eq('t0.name', $queryBuilder1->expr()->literal('test'))
            );

        $doctrinePaginator1 = new DoctrinePaginator($queryBuilder1);
        $doctrinePaginatorAdapter1 = new DoctrinePaginatorAdapter($doctrinePaginator1);

        $paginator1 = new LaminasPaginator($doctrinePaginatorAdapter1);
        $paginator1::setCache($cache);

        $queryBuilder2 = new QueryBuilder($entityManager);
        $queryBuilder2
            ->select('t0')
            ->from('Entity\City', 't0')
            ->where(
                $queryBuilder2->expr()->eq('t0.name', $queryBuilder2->expr()->literal('test2'))
            );

        $doctrinePaginator2 = new DoctrinePaginator($queryBuilder2);
        $doctrinePaginatorAdapter2 = new DoctrinePaginatorAdapter($doctrinePaginator2);

        $paginator2 = new LaminasPaginator($doctrinePaginatorAdapter2);
        $paginator2::setCache($cache);

        $paginator1->getItemsByPage(1); //_getCacheId() => Laminas_Paginator_1_07381ecd2347c3ccacd038f34ab9c699
        $paginator2->getItemsByPage(1); //_getCacheId() => Laminas_Paginator_1_07381ecd2347c3ccacd038f34ab9c699
```

`doctrine/doctrine-orm-module/src/DoctrineORMModule/Paginator/Adapter/DoctrinePaginator.php` shoud implement `\JsonSerializable`.
```php
public function jsonSerialize()
    {
        return [
            'select'       => $this->paginator->getQuery()->getSQL(),
            'count_select' => $this->paginator->count(),
        ];
    }
```

**Comment by TomHAnderson** [comment]
Is this the reason you think adding JsonSerilizable will fix the issue?

https://github.com/laminas/laminas-paginator/blob/2.11.x/src/Paginator.php#L906

**Comment by FabianKoestring** [comment]
> Is this the reason you think adding JsonSerilizable will fix the issue?
> 
> https://github.com/laminas/laminas-paginator/blob/2.11.x/src/Paginator.php#L906

Yea, am i wrong? 🤷‍♂️

**Comment by TomHAnderson** [comment]
No!  Not at all.  I just wanted to be sure we're on the same page.  I think your solution of adding JsonSerializable support is a non-intrusive method of fixing the problem you've described.  I'd like to go ahead with it.  Because you brought up the issue would you like to provide a PR?  If not, that's fine and I'll take care of it but I think you should give credit where credit is due.

**Comment by FabianKoestring** [comment]
> No! Not at all. I just wanted to be sure we're on the same page. I think your solution of adding JsonSerializable support is a non-intrusive method of fixing the problem you've described. I'd like to go ahead with it. Because you brought up the issue would you like to provide a PR? If not, that's fine and I'll take care of it but I think you should give credit where credit is due.

I will give it a try in the next few days. 👌
