### ISSUE TITLE
Deprecation of Serializable interface in PHP 8.1

### ISSUE THREAD

**Issue by Koen1999** [doctrine/DoctrineORMModule#695]
`Deprecated: DoctrineORMModule\Collector\MappingCollector implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in /code/vendor/doctrine/doctrine-orm-module/src/Collector/MappingCollector.php on line 21`

**Comment by snapshotpl** [comment]
Should be simple like https://github.com/laminas/laminas-developer-tools/pull/41

**Comment by snapshotpl** [comment]
We need to consider avoid using `--ignore-platform-req` in CI

**Comment by driehle** [comment]
Agreed, but this will only work once laminas-cache 2.x is dropped.
