### ISSUE TITLE
Typo in user guide documentation

### ISSUE THREAD

**Issue by ch-feedbackpeople** [doctrine/DoctrineORMModule#717]
I smashed my brain why the example given in the user guide under "Connection settings" didn't work in my environment, I always got a "driver class could not be found" exception. After an hour of debugging it turns out just to be a typo.

> 'driverClass' => \Doctrine\DBAL\Driver\PDO\MySql\Driver::class,

should be

> 'driverClass' => \Doctrine\DBAL\Driver\PDO\MySQL\Driver::class,

"MySQL" instead of "MySql"

**Comment by greg0ire** [comment]
Please send a pull request
