### ISSUE TITLE
"Specified key was too long; max key length is 767 bytes" - for version column

### ISSUE THREAD

**Issue by ittmann** [doctrine/DoctrineORMModule#720]
The default configured [version_column_length in module.config.php](https://github.com/doctrine/DoctrineORMModule/blob/5.3.x/config/module.config.php#L157) of 1024 is too long in MySQL/MariaDB with utf8mb4 (which is the default in MySQL 8.0 and MariaDB 10.5 and later)

This gives an error when running migrations:migrate for the first time or migrations:sync-metadata-storage when metadata storage needs to be synchronized

In doctrine/migrations it was reduced to 191.
See https://github.com/doctrine/migrations/issues/958 and https://github.com/doctrine/migrations/pull/960/files

**Comment by driehle** [comment]
Thanks for the report. Please provide a PR, this should be easy to fix.

**Comment by driehle** [comment]
Closed with 323eccfae756650c7ed8b6996c9c9ff37095ad03
