### ISSUE TITLE
Support Attributes instead of Annotations

### ISSUE THREAD

**Issue by boscho87** [doctrine/DoctrineORMModule#733]
With PHP 8 we have attributes available, it will make sense to use this instead of annotaitons.

```php
   /**
     * @ORM\Id
     * @ORM\Column(type="string")
     */
    protected string $hash;
    /**
     * @ORM\Column(type="string")
     */
    protected string $type = '';
```

```php
   #[ORM\Id]
   #[ORM\Column]
    protected string $hash;
   #[ORM\Column]
    protected string $type = '';
```

**Comment by driehle** [comment]
This is already supported for quite a while. Just make sure that in your entity configuration (https://www.doctrine-project.org/projects/doctrine-orm-module/en/5.3/user-guide.html#entities-settings) you are using `Doctrine\ORM\Mapping\Driver\AttributeDriver` and not `Doctrine\ORM\Mapping\Driver\AnnotationDriver`.

Feel free to provide a PR to update the documentation.
