### ISSUE TITLE
Upgrade `doctrine/DoctrineModule` to v6

### ISSUE THREAD

**Issue by Koen1999** [doctrine/DoctrineORMModule#735]
`doctrine/DoctrineModule` can be upgraded to v6.
The most prominent change is the changes to the caching dependencies.
As a result of this upgrade, we can drop the dependency on the deprecated doctrine/cache

Please see:
https://github.com/doctrine/DoctrineModule/releases

**Comment by Koen1999** [comment]
I also just noticed that the maintainers are already working on this in PR: https://github.com/doctrine/DoctrineORMModule/pull/734

My compliments!

**Comment by demiankatz** [comment]
@Koen1999, I'm not a maintainer on this project, just the contributor of #734. I'm hoping somebody with more power can give my work a review soon!
