### ISSUE TITLE
Cache dir change since updagrade to doctrine/cache:^2

### ISSUE THREAD

**Issue by fezfez** [doctrine/DoctrineORMModule#740]
Hello !

My cache dir has change since i have migrated to doctrine/cache:^2, he now target `data/DoctrineModule/cache/`

How to change it ?

Thanks

**Comment by TomHAnderson** [comment]
This is a DoctrineModule question.  The configuration is here:  https://github.com/doctrine/DoctrineModule/blob/6.0.x/src/ConfigProvider.php#L131
