### ISSUE TITLE
Error Cache instance with Laminas Di

### ISSUE THREAD

**Issue by wilmeryarkan** [doctrine/DoctrineORMModule#742]
I am updating my slides project and their respective libraries, one of them is Slides DI, which is generating a kind of conflict with Slides Cache instance (Memory).

` Uncaught Laminas\Di\Exception\MissingPropertyException: Could not resolve value for parameter "storage" of type Laminas\Cache\Storage\StorageInterface in class DoctrineModule\Cache\LaminasStorageCache (requested as DoctrineModule\Cache\LaminasStorageCache) in /apps/events/vendor/laminas/laminas-di/src/Resolver/DependencyResolver.php`

The error occurs when trying to instantiate by container LaminasStorageCache in CacheFactory class, and DI looks for its respective parameter in the constructor, and it can't resolve it correctly unless it is defined by Di configuration.

DoctrineModule\Service\CacheFactory.php
![image](https://github.com/doctrine/DoctrineORMModule/assets/71442759/041a5f0e-a458-4fa1-b0a1-c4d9dafb710d)

Di config:
![image](https://github.com/doctrine/DoctrineORMModule/assets/71442759/300bbbec-e5ff-44ad-b1c4-f372e19c0ba4)

The problem with this solution that is not flexible when change other type of cache (redis, memcached, etc).

Have any type of consideration to work with Laminas\Di of maybe have a best solution for this problem?

Thanks.

**Comment by TomHAnderson** [comment]
Is your problem a DI issue?  Can this be solved using a factory?

**Comment by TomHAnderson** [comment]
Closing as cache has moved to DoctrineModule and been revamped with 6.x
