### ISSUE TITLE
PHP 8.3 support

### ISSUE THREAD

**Issue by FabianKoestring** [doctrine/DoctrineORMModule#748]
Are there any plan to support `php` `8.3.0` in the near future?

**Comment by driehle** [comment]
This module depends on [doctrine-laminas-hydrator](https://github.com/doctrine/doctrine-laminas-hydrator), which with [3.4.0](https://github.com/doctrine/doctrine-laminas-hydrator/releases/tag/3.4.0) has already received PHP 8.3 support, and [doctrine-module](https://github.com/doctrine/DoctrineModule), which still waits for PHP 8.3 support.

Feel free to provide a PR to push this forward. We will, however, first need to care about doctrine-module, then about doctrine-orm-module.

**Comment by TomHAnderson** [comment]
I've started a branch for this repository and I'll get DoctrineModule updated too.  Hope to make those PRs this weekend.

**Comment by TomHAnderson** [comment]
See https://github.com/doctrine/DoctrineORMModule/pull/749 for the state of 8.3 support

**Comment by driehle** [comment]
Closed with #749
